# -*- coding: utf-8 -*-
"""NN_RS_MohammadAminKiani_4043644008.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kc-BlDq9UCIfUPPHaDDywEAaBCWcuAZw

# Mohammad Amin Kiani 4043644008

## pc eng - AI 404

### NN-Rs . ui.ac.ir

## 0-
"""

# !git clone https://github.com/nelson1425/EfficientAD.git

"""- کلون کردن پیاده‌سازی غیررسمی EfficientAD (مخزن nelson1425/EfficientAD یا نسخه مشابه)
- دانلود و آماده‌سازی حداقل ۲ دیتاستِ استفاده‌شده در مقاله (**MVTec AD** و **MVTec LOCO AD**)
- (اختیاری) دانلود یک دیتاست عمومی شبیه ImageNet برای **penalty** (اینجا: **Imagenette**)
- اجرای آموزش + تست و ذخیره **anomaly maps** (خروجی .tiff)
- ثبت تمام lossها و متریک‌های مهم در **TensorBoard** (برای Train و Test)
- اجرای اسکریپت‌های ارزیابی رسمیِ MVTec و تولید فایل‌های متریک (در صورت فعال بودن)
- ساخت یک **PDF تک‌صفحه‌ای** برای قیاس نتایج (خلاصه)
- گزارش مسیر/حجم وزن‌های ذخیره‌شده برای هر دیتاست/کلاس اجرا شده

> `TRAIN_STEPS=70000` و `MODEL_SIZE='medium'`

## 1-
"""

# =========================
# 1) GPU Check + Libraries
# =========================
import os, sys, platform, shutil, json, re, math, time
from pathlib import Path

import torch
print("Python:", sys.version)
print("Platform:", platform.platform())
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# نصب کتابخانه‌های لازم (بدون downgrade کردن torch)
!pip -q install --upgrade pip
!pip -q install tqdm tifffile scikit-learn pandas matplotlib reportlab tensorboard gdown tabulate scikit-image

"""## 2-"""

# Commented out IPython magic to ensure Python compatibility.

# =========================
# 2) Clone Repo
# =========================
# %cd /content
if not Path("EfficientAD").exists():
    !git clone --depth 1 https://github.com/nelson1425/EfficientAD.git
# %cd /content/EfficientAD

# نمایش فایل‌ها
!ls -la

"""## 3-"""

# =======================================================
# 3) Teacher weights (fallback download if missing)
# =======================================================
from pathlib import Path
import urllib.request

models_dir = Path("/content/EfficientAD/models")
models_dir.mkdir(parents=True, exist_ok=True)

hf_teacher_small = "https://huggingface.co/adghin/efficientAD_weights/resolve/main/teacher/teacher_small.pth"
hf_teacher_medium = "https://huggingface.co/adghin/efficientAD_weights/resolve/main/teacher/teacher_medium.pth"

def ensure_file(path: Path, url: str):
    if path.exists() and path.stat().st_size > 0:
        print(f"[OK] exists: {path} ({path.stat().st_size/1e6:.1f} MB)")
        return
    print(f"[DL] downloading -> {path.name}")
    urllib.request.urlretrieve(url, path.as_posix())
    print(f"[OK] downloaded: {path} ({path.stat().st_size/1e6:.1f} MB)")

# اگر فایل‌های وزن داخل ریپو نبودند، از HF دانلود می‌کنیم:
ensure_file(models_dir/"teacher_small.pth", hf_teacher_small)
ensure_file(models_dir/"teacher_medium.pth", hf_teacher_medium)

!ls -lh /content/EfficientAD/models

"""## 4-"""

# # =======================================================
# # 4) Download Datasets: MVTec AD + MVTec LOCO AD
# #    (Links from the repo README)
# # =======================================================
# %cd /content

# DATA_DIR = Path("/content/datasets")
# DATA_DIR.mkdir(parents=True, exist_ok=True)

# MVTEC_AD_URL = "https://www.mydrive.ch/shares/38536/3830184030e49fe74747669442f0f282/download/420938113-1629952094/mvtec_anomaly_detection.tar.xz"
# MVTEC_LOCO_URL = "https://www.mydrive.ch/shares/48237/1b9106ccdfbb09a0c414bd49fe44a14a/download/430647091-1646842701/mvtec_loco_anomaly_detection.tar.xz"

# def download_and_extract(url: str, out_dir: Path, out_name: str):
#     out_dir.mkdir(parents=True, exist_ok=True)
#     archive_path = out_dir/out_name
#     if not archive_path.exists():
#         print(f"[DL] {out_name}")
#         !wget -q --show-progress -O "{archive_path}" "{url}"
#     else:
#         print(f"[OK] archive exists: {archive_path}")
#     # Extract (if not already)
#     marker = out_dir/(out_name + ".extracted")
#     if not marker.exists():
#         print("[EXTRACT] ...")
#         !tar -xf "{archive_path}" -C "{out_dir}"
#         marker.write_text("ok")
#     else:
#         print("[OK] already extracted")

# download_and_extract(MVTEC_AD_URL, DATA_DIR, "mvtec_anomaly_detection.tar.xz")
# download_and_extract(MVTEC_LOCO_URL, DATA_DIR, "mvtec_loco_anomaly_detection.tar.xz")

# # Resolve actual roots (sometimes tar contains an extra nested folder)
# def resolve_root(root: Path, expected_subfolder: str):
#     # expected_subfolder مثل bottle یا breakfast_box
#     if (root/expected_subfolder).exists():
#         return root
#     # اگر داخل root یک پوشه‌ی هم‌نام وجود داشته باشد
#     for cand in root.iterdir():
#         if cand.is_dir() and (cand/expected_subfolder).exists():
#             return cand
#     return root  # fallback

# MVTEC_AD_ROOT = resolve_root(DATA_DIR/"mvtec_anomaly_detection", "bottle")
# MVTEC_LOCO_ROOT = resolve_root(DATA_DIR/"mvtec_loco_anomaly_detection", "breakfast_box")

# print("MVTEC_AD_ROOT:", MVTEC_AD_ROOT)
# print("MVTEC_LOCO_ROOT:", MVTEC_LOCO_ROOT)

# print("\n[Sample folders under MVTec AD root]")
# !ls -1 "{MVTEC_AD_ROOT}" | head -n 20

# print("\n[Sample folders under MVTec LOCO root]")
# !ls -1 "{MVTEC_LOCO_ROOT}" | head -n 20

"""مشکل از لینک‌های مای درایو داخل ریدمی ریپو است که قدیمی شده‌اند
https://www.mydrive.ch/shares/38536/3830184030e49fe74747669442f0f282/download/420938113-1629952094/mvtec_anomaly_detection.tar.xz
"""

# !rm -f /content/datasets/*.extracted
# !rm -f /content/datasets/mvtec_anomaly_detection.tar.xz
# !rm -f /content/datasets/mvtec_loco_anomaly_detection.tar.xz
# !ls -la /content/datasets | head -n 50

"""اگر دانلود کل دیتاست شکست خورد (باز هم محدودیت سرور)، خودکار می‌رود سراغ دانلود یکی/چند کلاس کوچک‌تر (مثل bottle.tar.xz)"""

# Commented out IPython magic to ensure Python compatibility.
# =======================================================
# 4) Download/Extract Datasets (UPDATED LINKS + FALLBACK)
# =======================================================
# %cd /content
from pathlib import Path
import subprocess

def sh(cmd):
    print(">>", cmd)
    subprocess.run(["bash","-lc", cmd], check=True)

DATA_DIR = Path("/content/datasets")
DATA_DIR.mkdir(parents=True, exist_ok=True)

#  لینک‌های قدیمی ریپو 404 شده‌اند؛ این‌ها لینک‌های جدید صفحه رسمی دانلود هستند
# (MVTec AD downloads -> mydrive)
MVTEC_AD_URL_NEW = "https://www.mydrive.ch/shares/38536/3830184030e49fe74747669442f0f283/download/420938113-1629960298/mvtec_anomaly_detection.tar.xz"
# (یک fallback کوچک‌تر: فقط Bottle)
MVTEC_AD_BOTTLE_URL = "https://www.mydrive.ch/shares/38536/3830184030e49fe74747669442f0f283/download/420937370-1629958698/bottle.tar.xz"

# LOCO (همان لینک صفحه رسمی؛ اگر full سخت بود، می‌توانی فقط breakfast_box را بگیری)
MVTEC_LOCO_URL = "https://www.mydrive.ch/shares/48237/1b9106ccdfbb09a0c414bd49fe44a14a/download/430647091-1646842701/mvtec_loco_anomaly_detection.tar.xz"
MVTEC_LOCO_BREAKFAST_URL = "https://www.mydrive.ch/shares/48238/d94999f7d56b82c26cc22e36a8cfe02b/download/430647124-1646843193/breakfast_box.tar.xz"

# ابزار دانلود پایدارتر
sh("apt-get -qq update && apt-get -qq install -y aria2 ca-certificates curl >/dev/null")

UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"

def download(url, out_path: Path):
    tmp = out_path.with_suffix(out_path.suffix + ".tmp")
    if tmp.exists(): tmp.unlink()
    try:
        sh(f"aria2c -x 16 -s 16 -k 1M --file-allocation=none --max-tries=10 --retry-wait=3 "
           f"--user-agent='{UA}' -o '{tmp.name}' -d '{tmp.parent}' '{url}'")
    except subprocess.CalledProcessError:
        sh(f"curl -L --fail --retry 10 --retry-all-errors --retry-delay 3 -A '{UA}' -o '{tmp}' '{url}'")
    tmp.replace(out_path)
    sh(f"ls -lh '{out_path}'")

def tar_ok(path: Path) -> bool:
    try:
        sh(f"tar -tf '{path}' >/dev/null 2>&1")
        return True
    except subprocess.CalledProcessError:
        return False

def extract(archive: Path, out_dir: Path):
    sh(f"tar -xf '{archive}' -C '{out_dir}'")

# ---------------------------
# 4.1) MVTec AD (try full -> fallback bottle)
# ---------------------------
mvtec_ad_root = DATA_DIR / "mvtec_anomaly_detection"
mvtec_ad_root.mkdir(exist_ok=True)

full_ad = DATA_DIR / "mvtec_anomaly_detection.tar.xz"
if not full_ad.exists():
    print("[DL] MVTec AD (full) ...")
    try:
        download(MVTEC_AD_URL_NEW, full_ad)
    except subprocess.CalledProcessError:
        pass

need_extract_full = (not (mvtec_ad_root/"bottle").exists())
if full_ad.exists() and tar_ok(full_ad) and need_extract_full:
    print("[EXTRACT] full MVTec AD ...")
    extract(full_ad, DATA_DIR)

# اگر هنوز bottle وجود ندارد => fallback فقط bottle.tar.xz را دانلود کن
if not (mvtec_ad_root/"bottle").exists():
    print("[FALLBACK] full download failed -> downloading bottle only ...")
    bottle_arc = DATA_DIR / "bottle.tar.xz"
    if not bottle_arc.exists():
        download(MVTEC_AD_BOTTLE_URL, bottle_arc)
    assert tar_ok(bottle_arc), "bottle.tar.xz is not a valid tar file"
    extract(bottle_arc, mvtec_ad_root)

# ---------------------------
# 4.2) MVTec LOCO (try full -> fallback breakfast_box)
# ---------------------------
mvtec_loco_root = DATA_DIR / "mvtec_loco_anomaly_detection"
mvtec_loco_root.mkdir(exist_ok=True)

full_loco = DATA_DIR / "mvtec_loco_anomaly_detection.tar.xz"
if not full_loco.exists():
    print("[DL] MVTec LOCO (full) ...")
    try:
        download(MVTEC_LOCO_URL, full_loco)
    except subprocess.CalledProcessError:
        pass

need_extract_loco = (not (mvtec_loco_root/"breakfast_box").exists())
if full_loco.exists() and tar_ok(full_loco) and need_extract_loco:
    print("[EXTRACT] full MVTec LOCO ...")
    extract(full_loco, DATA_DIR)

if not (mvtec_loco_root/"breakfast_box").exists():
    print("[FALLBACK] full LOCO failed -> downloading breakfast_box only ...")
    bb_arc = DATA_DIR / "breakfast_box.tar.xz"
    if not bb_arc.exists():
        download(MVTEC_LOCO_BREAKFAST_URL, bb_arc)
    assert tar_ok(bb_arc), "breakfast_box.tar.xz is not a valid tar file"
    extract(bb_arc, mvtec_loco_root)

MVTEC_AD_ROOT = mvtec_ad_root
MVTEC_LOCO_ROOT = mvtec_loco_root

print("\n✅ MVTEC_AD_ROOT:", MVTEC_AD_ROOT)
print("✅ MVTEC_LOCO_ROOT:", MVTEC_LOCO_ROOT)

print("\n[MVTec AD sample]")
sh(f"ls -1 '{MVTEC_AD_ROOT}' | head -n 20")

print("\n[MVTec LOCO sample]")
sh(f"ls -1 '{MVTEC_LOCO_ROOT}' | head -n 20")

!ls -la /content/datasets/mvtec_anomaly_detection | head -n 50
!ls -la /content/datasets/mvtec_anomaly_detection/bottle | head -n 50
!ls -la /content/datasets/mvtec_anomaly_detection/bottle/train | head -n 50
!ls -la /content/datasets/mvtec_anomaly_detection/bottle/test | head -n 50

!ls -la /content/datasets/mvtec_loco_anomaly_detection | head -n 50
!ls -la /content/datasets/mvtec_loco_anomaly_detection/breakfast_box | head -n 50
!ls -la /content/datasets/mvtec_loco_anomaly_detection/breakfast_box/train | head -n 50
!ls -la /content/datasets/mvtec_loco_anomaly_detection/breakfast_box/test | head -n 50

"""## 5-"""

# Commented out IPython magic to ensure Python compatibility.

# =======================================================
# 5) (Optional) Imagenette as ImageNet-like penalty dataset
#    EfficientAD expects a folder with subfolders of images.
# =======================================================
# %cd /content/datasets

IMAGENETTE_URL = "https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz"
IMAGENETTE_TGZ = Path("imagenette2-160.tgz")
IMAGENETTE_DIR = Path("imagenette2-160")

if not IMAGENETTE_DIR.exists():
    if not IMAGENETTE_TGZ.exists():
        print("[DL] imagenette2-160.tgz")
        !wget -q --show-progress -O "{IMAGENETTE_TGZ}" "{IMAGENETTE_URL}"
    print("[EXTRACT] imagenette2-160.tgz")
    !tar -xf "{IMAGENETTE_TGZ}"
else:
    print("[OK] Imagenette already exists")

IMAGENETTE_TRAIN = (Path("/content/datasets")/IMAGENETTE_DIR/"train")
print("IMAGENETTE_TRAIN:", IMAGENETTE_TRAIN)
!ls -1 "{IMAGENETTE_TRAIN}" | head

"""## 6-"""

!pip -q install tifffile scikit-image scikit-learn tensorboard

# Commented out IPython magic to ensure Python compatibility.
# =======================================================
# 6) Create efficientad_tb.py WITHOUT %%writefile (FIXED)
# =======================================================
# %cd /content/EfficientAD
from pathlib import Path

code = r"""#!/usr/bin/python
# -*- coding: utf-8 -*-

import numpy as np
import tifffile
import torch
from torch.utils.data import DataLoader
from torchvision import transforms
from torch.utils.tensorboard import SummaryWriter

import argparse
import itertools
import os
import random
from pathlib import Path
from tqdm import tqdm
from sklearn.metrics import roc_auc_score

from common import (
    get_autoencoder,
    get_pdn_small,
    get_pdn_medium,
    ImageFolderWithoutTarget,
    ImageFolderWithPath,
    InfiniteDataloader,
)

def get_argparse():
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--dataset', default='mvtec_ad', choices=['mvtec_ad', 'mvtec_loco'])
    parser.add_argument('-s', '--subdataset', default='bottle',
                        help='One of 15 sub-datasets of Mvtec AD or 5 sub-datasets of Mvtec LOCO')
    parser.add_argument('-o', '--output_dir', default='output/1')
    parser.add_argument('-m', '--model_size', default='small', choices=['small', 'medium'])
    parser.add_argument('-w', '--weights', default='models/teacher_small.pth')
    parser.add_argument('-i', '--imagenet_train_path', default='none',
                        help='Set to "none" to disable ImageNet pretraining penalty.')
    parser.add_argument('-a', '--mvtec_ad_path', default='./mvtec_anomaly_detection',
                        help='Downloaded Mvtec AD dataset root')
    parser.add_argument('-b', '--mvtec_loco_path', default='./mvtec_loco_anomaly_detection',
                        help='Downloaded Mvtec LOCO dataset root')
    parser.add_argument('-t', '--train_steps', type=int, default=70000)

    # Colab-friendly extras
    parser.add_argument('--num_workers', type=int, default=2)
    parser.add_argument('--tb_log_every', type=int, default=10)
    parser.add_argument('--tb_eval_every', type=int, default=10000)
    parser.add_argument('--save_every', type=int, default=1000)
    parser.add_argument('--seed', type=int, default=42)
    return parser.parse_args()

# ---- constants
on_gpu = torch.cuda.is_available()
out_channels = 384
image_size = 256

# ---- transforms
default_transform = transforms.Compose([
    transforms.Resize((image_size, image_size)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

transform_ae = transforms.RandomChoice([
    transforms.ColorJitter(brightness=0.2),
    transforms.ColorJitter(contrast=0.2),
    transforms.ColorJitter(saturation=0.2)
])

def train_transform(image):
    return default_transform(image), default_transform(transform_ae(image))

@torch.no_grad()
def teacher_normalization(teacher, train_loader):
    mean_outputs = []
    for train_image, _ in tqdm(train_loader, desc='Computing mean of features'):
        if on_gpu:
            train_image = train_image.cuda(non_blocking=True)
        teacher_output = teacher(train_image)
        mean_output = torch.mean(teacher_output, dim=[0, 2, 3])
        mean_outputs.append(mean_output)
    channel_mean = torch.mean(torch.stack(mean_outputs), dim=0)
    channel_mean = channel_mean[None, :, None, None]

    mean_distances = []
    for train_image, _ in tqdm(train_loader, desc='Computing std of features'):
        if on_gpu:
            train_image = train_image.cuda(non_blocking=True)
        teacher_output = teacher(train_image)
        distance = (teacher_output - channel_mean) ** 2
        mean_distance = torch.mean(distance, dim=[0, 2, 3])
        mean_distances.append(mean_distance)
    channel_var = torch.mean(torch.stack(mean_distances), dim=0)
    channel_var = channel_var[None, :, None, None]
    channel_std = torch.sqrt(channel_var + 1e-12)
    return channel_mean, channel_std

@torch.no_grad()
def predict(image, teacher, student, autoencoder, teacher_mean, teacher_std,
            q_st_start=None, q_st_end=None, q_ae_start=None, q_ae_end=None):
    teacher_output = teacher(image)
    teacher_output = (teacher_output - teacher_mean) / teacher_std
    student_output = student(image)
    autoencoder_output = autoencoder(image)

    map_st = torch.mean((teacher_output - student_output[:, :out_channels]) ** 2, dim=1, keepdim=True)
    map_ae = torch.mean((autoencoder_output - student_output[:, out_channels:]) ** 2, dim=1, keepdim=True)

    if q_st_start is not None:
        map_st = 0.1 * (map_st - q_st_start) / (q_st_end - q_st_start + 1e-12)
    if q_ae_start is not None:
        map_ae = 0.1 * (map_ae - q_ae_start) / (q_ae_end - q_ae_start + 1e-12)

    map_combined = 0.5 * map_st + 0.5 * map_ae
    return map_combined, map_st, map_ae

@torch.no_grad()
def map_normalization(validation_loader, teacher, student, autoencoder, teacher_mean, teacher_std,
                      desc='Map normalization'):
    maps_st = []
    maps_ae = []
    for image, _ in tqdm(validation_loader, desc=desc):
        if on_gpu:
            image = image.cuda(non_blocking=True)
        _, map_st, map_ae = predict(
            image=image, teacher=teacher, student=student, autoencoder=autoencoder,
            teacher_mean=teacher_mean, teacher_std=teacher_std
        )
        maps_st.append(map_st)
        maps_ae.append(map_ae)

    maps_st = torch.cat(maps_st)
    maps_ae = torch.cat(maps_ae)

    q_st_start = torch.quantile(maps_st, q=0.9)
    q_st_end = torch.quantile(maps_st, q=0.995)
    q_ae_start = torch.quantile(maps_ae, q=0.9)
    q_ae_end = torch.quantile(maps_ae, q=0.995)
    return q_st_start, q_st_end, q_ae_start, q_ae_end

def test(test_set, teacher, student, autoencoder, teacher_mean, teacher_std,
         q_st_start, q_st_end, q_ae_start, q_ae_end,
         test_output_dir=None, desc='Running inference'):
    y_true = []
    y_score = []

    for image, target, path in tqdm(test_set, desc=desc):
        orig_width = image.width
        orig_height = image.height

        image_t = default_transform(image)[None]
        if on_gpu:
            image_t = image_t.cuda(non_blocking=True)

        map_combined, _, _ = predict(
            image=image_t, teacher=teacher, student=student, autoencoder=autoencoder,
            teacher_mean=teacher_mean, teacher_std=teacher_std,
            q_st_start=q_st_start, q_st_end=q_st_end, q_ae_start=q_ae_start, q_ae_end=q_ae_end
        )

        map_combined = torch.nn.functional.pad(map_combined, (4, 4, 4, 4))
        map_combined = torch.nn.functional.interpolate(map_combined, (orig_height, orig_width), mode='bilinear')
        map_combined = map_combined[0, 0].detach().cpu().numpy()

        defect_class = os.path.basename(os.path.dirname(path))

        if test_output_dir is not None:
            img_nm = os.path.split(path)[1].split('.')[0]
            out_dir = Path(test_output_dir) / defect_class
            out_dir.mkdir(parents=True, exist_ok=True)
            file = out_dir / f"{img_nm}.tiff"
            tifffile.imwrite(file.as_posix(), map_combined)

        y_true_image = 0 if defect_class == 'good' else 1
        y_score_image = float(np.max(map_combined))
        y_true.append(y_true_image)
        y_score.append(y_score_image)

    auc = roc_auc_score(y_true=y_true, y_score=y_score)
    return auc * 100.0

def main():
    config = get_argparse()
    seed = config.seed
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

    if config.dataset == 'mvtec_ad':
        dataset_path = config.mvtec_ad_path
    elif config.dataset == 'mvtec_loco':
        dataset_path = config.mvtec_loco_path
    else:
        raise Exception('Unknown config.dataset')

    pretrain_penalty = (config.imagenet_train_path != 'none')

    train_output_dir = os.path.join(config.output_dir, 'trainings', config.dataset, config.subdataset)
    test_output_dir = os.path.join(config.output_dir, 'anomaly_maps', config.dataset, config.subdataset, 'test')
    os.makedirs(train_output_dir, exist_ok=True)
    os.makedirs(test_output_dir, exist_ok=True)

    tb_dir = os.path.join(train_output_dir, "tensorboard")
    writer = SummaryWriter(log_dir=tb_dir)
    writer.add_text("run/config", str(vars(config)))

    full_train_set = ImageFolderWithoutTarget(
        os.path.join(dataset_path, config.subdataset, 'train'),
        transform=transforms.Lambda(train_transform)
    )
    test_set = ImageFolderWithPath(os.path.join(dataset_path, config.subdataset, 'test'))

    if config.dataset == 'mvtec_ad':
        train_size = int(0.9 * len(full_train_set))
        validation_size = len(full_train_set) - train_size
        rng = torch.Generator().manual_seed(seed)
        train_set, validation_set = torch.utils.data.random_split(full_train_set, [train_size, validation_size], rng)
    elif config.dataset == 'mvtec_loco':
        train_set = full_train_set
        validation_set = ImageFolderWithoutTarget(
            os.path.join(dataset_path, config.subdataset, 'validation'),
            transform=transforms.Lambda(train_transform)
        )
    else:
        raise Exception('Unknown config.dataset')

    train_loader = DataLoader(train_set, batch_size=1, shuffle=True,
                              num_workers=config.num_workers, pin_memory=True)
    train_loader_infinite = InfiniteDataloader(train_loader)
    validation_loader = DataLoader(validation_set, batch_size=1, num_workers=0)

    if pretrain_penalty:
        penalty_transform = transforms.Compose([
            transforms.Resize((2 * image_size, 2 * image_size)),
            transforms.RandomGrayscale(0.3),
            transforms.CenterCrop(image_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])
        penalty_set = ImageFolderWithoutTarget(config.imagenet_train_path, transform=penalty_transform)
        penalty_loader = DataLoader(penalty_set, batch_size=1, shuffle=True,
                                    num_workers=config.num_workers, pin_memory=True)
        penalty_loader_infinite = InfiniteDataloader(penalty_loader)
    else:
        penalty_loader_infinite = itertools.repeat(None)

    if config.model_size == 'small':
        teacher = get_pdn_small(out_channels)
        student = get_pdn_small(2 * out_channels)
    elif config.model_size == 'medium':
        teacher = get_pdn_medium(out_channels)
        student = get_pdn_medium(2 * out_channels)
    else:
        raise Exception('Unknown model_size')

    state_dict = torch.load(config.weights, map_location='cpu')
    teacher.load_state_dict(state_dict)
    autoencoder = get_autoencoder(out_channels)

    teacher.eval()
    student.train()
    autoencoder.train()

    if on_gpu:
        teacher.cuda()
        student.cuda()
        autoencoder.cuda()

    teacher_mean, teacher_std = teacher_normalization(teacher, train_loader)

    optimizer = torch.optim.Adam(
        itertools.chain(student.parameters(), autoencoder.parameters()),
        lr=1e-4,
        weight_decay=1e-5
    )
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=int(0.95 * config.train_steps), gamma=0.1)

    tqdm_obj = tqdm(range(config.train_steps))
    for iteration, (image_st, image_ae), image_penalty in zip(tqdm_obj, train_loader_infinite, penalty_loader_infinite):
        if on_gpu:
            image_st = image_st.cuda(non_blocking=True)
            image_ae = image_ae.cuda(non_blocking=True)
            if image_penalty is not None:
                image_penalty = image_penalty.cuda(non_blocking=True)

        with torch.no_grad():
            teacher_output_st = teacher(image_st)
            teacher_output_st = (teacher_output_st - teacher_mean) / teacher_std

        student_output_st = student(image_st)[:, :out_channels]
        distance_st = (teacher_output_st - student_output_st) ** 2
        d_hard = torch.quantile(distance_st, q=0.999)
        loss_hard = torch.mean(distance_st[distance_st >= d_hard])

        if image_penalty is not None:
            student_output_penalty = student(image_penalty)[:, :out_channels]
            loss_penalty = torch.mean(student_output_penalty ** 2)
            loss_st = loss_hard + loss_penalty
        else:
            loss_penalty = torch.tensor(0.0, device=loss_hard.device)
            loss_st = loss_hard

        ae_output = autoencoder(image_ae)
        with torch.no_grad():
            teacher_output_ae = teacher(image_ae)
            teacher_output_ae = (teacher_output_ae - teacher_mean) / teacher_std

        student_output_ae = student(image_ae)[:, out_channels:]
        distance_ae = (teacher_output_ae - ae_output) ** 2
        distance_stae = (ae_output - student_output_ae) ** 2
        loss_ae = torch.mean(distance_ae)
        loss_stae = torch.mean(distance_stae)

        loss_total = loss_st + loss_ae + loss_stae

        optimizer.zero_grad(set_to_none=True)
        loss_total.backward()
        optimizer.step()
        scheduler.step()

        if iteration % config.tb_log_every == 0:
            writer.add_scalar("train/loss_total", loss_total.item(), iteration)
            writer.add_scalar("train/loss_st", loss_st.item(), iteration)
            writer.add_scalar("train/loss_hard", loss_hard.item(), iteration)
            writer.add_scalar("train/loss_penalty", loss_penalty.item(), iteration)
            writer.add_scalar("train/loss_ae", loss_ae.item(), iteration)
            writer.add_scalar("train/loss_stae", loss_stae.item(), iteration)
            writer.add_scalar("train/lr", optimizer.param_groups[0]["lr"], iteration)

        if iteration % 10 == 0:
            tqdm_obj.set_description(f"loss={loss_total.item():.4f} st={loss_st.item():.4f} ae={loss_ae.item():.4f} stae={loss_stae.item():.4f}")

        if iteration % config.save_every == 0 and iteration > 0:
            torch.save(teacher, os.path.join(train_output_dir, 'teacher_tmp.pth'))
            torch.save(student, os.path.join(train_output_dir, 'student_tmp.pth'))
            torch.save(autoencoder, os.path.join(train_output_dir, 'autoencoder_tmp.pth'))

        if iteration % config.tb_eval_every == 0 and iteration > 0:
            teacher.eval(); student.eval(); autoencoder.eval()
            q_st_start, q_st_end, q_ae_start, q_ae_end = map_normalization(
                validation_loader=validation_loader,
                teacher=teacher, student=student, autoencoder=autoencoder,
                teacher_mean=teacher_mean, teacher_std=teacher_std,
                desc='Intermediate map normalization'
            )
            auc = test(
                test_set=test_set,
                teacher=teacher, student=student, autoencoder=autoencoder,
                teacher_mean=teacher_mean, teacher_std=teacher_std,
                q_st_start=q_st_start, q_st_end=q_st_end, q_ae_start=q_ae_start, q_ae_end=q_ae_end,
                test_output_dir=None,
                desc='Intermediate inference'
            )
            print(f"Intermediate image auc: {auc:.4f}")
            writer.add_scalar("test/intermediate_image_auc", auc, iteration)
            teacher.eval(); student.train(); autoencoder.train()

    teacher.eval(); student.eval(); autoencoder.eval()

    torch.save(teacher, os.path.join(train_output_dir, 'teacher_final.pth'))
    torch.save(student, os.path.join(train_output_dir, 'student_final.pth'))
    torch.save(autoencoder, os.path.join(train_output_dir, 'autoencoder_final.pth'))

    q_st_start, q_st_end, q_ae_start, q_ae_end = map_normalization(
        validation_loader=validation_loader,
        teacher=teacher, student=student, autoencoder=autoencoder,
        teacher_mean=teacher_mean, teacher_std=teacher_std,
        desc='Final map normalization'
    )
    auc = test(
        test_set=test_set,
        teacher=teacher, student=student, autoencoder=autoencoder,
        teacher_mean=teacher_mean, teacher_std=teacher_std,
        q_st_start=q_st_start, q_st_end=q_st_end, q_ae_start=q_ae_start, q_ae_end=q_ae_end,
        test_output_dir=test_output_dir,
        desc='Final inference'
    )
    print(f"Final image auc: {auc:.4f}")
    writer.add_scalar("test/final_image_auc", auc, config.train_steps)

    metrics = {
        "dataset": config.dataset,
        "subdataset": config.subdataset,
        "model_size": config.model_size,
        "train_steps": config.train_steps,
        "final_image_auc": float(auc),
        "tb_dir": tb_dir,
        "train_output_dir": train_output_dir,
        "test_output_dir": test_output_dir,
        "pretrain_penalty": bool(pretrain_penalty),
    }
    with open(os.path.join(train_output_dir, "final_metrics.json"), "w") as f:
        import json
        json.dump(metrics, f, indent=2)

    writer.flush()
    writer.close()

if __name__ == '__main__':
    main()
"""

Path("efficientad_tb.py").write_text(code, encoding="utf-8")
print("✅ written:", Path("efficientad_tb.py").resolve())
!python -c "import efficientad_tb; print('✅ import ok')"

"""## 7-"""

# # =======================================================
# # 7) Run EfficientAD on >=2 datasets (MVTec AD + LOCO)
# #    انتخاب دسته‌ها:
# #    - برای اجرای کامل، لیست FULL را استفاده کن.
# #    - برای تست سریع پایپ‌لاین، لیست QUICK را.
# # =======================================================
# %cd /content/EfficientAD

# from pathlib import Path
# import subprocess, json, pandas as pd

# # ---- تنظیمات اصلی
# OUTPUT_DIR = Path("/content/outputs/efficientad_runs")
# OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# MODEL_SIZE = "medium"      # "small" یا "medium"
# TRAIN_STEPS = 70000        # برای تست سریع: مثلا 2000 یا 10000
# USE_PENALTY = True         # اگر False شود، --imagenet_train_path none می‌شود.

# # TRAIN_STEPS = 2000
# # MODEL_SIZE = "small"
# # USE_PENALTY = True


# TEACHER_WEIGHTS = "/content/EfficientAD/models/teacher_medium.pth" if MODEL_SIZE=="medium" else "/content/EfficientAD/models/teacher_small.pth"
# IMAGENET_TRAIN_PATH = str(IMAGENETTE_TRAIN) if USE_PENALTY else "none"

# # ---- دسته‌های پیشنهادی (برای تست سریع)
# MVTEC_AD_OBJECTS_QUICK = ["bottle", "cable"]
# MVTEC_LOCO_OBJECTS_QUICK = ["breakfast_box", "juice_bottle"]

# # ---- اجرای کامل (تمام کلاس‌ها)
# MVTEC_AD_OBJECTS_FULL = ["carpet","grid","leather","tile","wood","bottle","cable","capsule","hazelnut","metal_nut","pill","screw","toothbrush","transistor","zipper"]
# MVTEC_LOCO_OBJECTS_FULL = ["breakfast_box","juice_bottle","pushpins","screw_bag","splicing_connectors"]

# # انتخاب لیست نهایی (اینجا روی QUICK گذاشتم؛ اگر می‌خواهی کامل اجرا شود FULL را جایگزین کن)
# # MVTEC_AD_OBJECTS = MVTEC_AD_OBJECTS_QUICK
# # MVTEC_LOCO_OBJECTS = MVTEC_LOCO_OBJECTS_QUICK

# MVTEC_AD_OBJECTS = MVTEC_AD_OBJECTS_FULL
# MVTEC_LOCO_OBJECTS = MVTEC_LOCO_OBJECTS_FULL

# def run_one(dataset: str, subdataset: str, dataset_root: str):
#     cmd = [
#         "python", "efficientad_tb.py",
#         "--dataset", dataset,
#         "--subdataset", subdataset,
#         "--output_dir", str(OUTPUT_DIR),
#         "--model_size", MODEL_SIZE,
#         "--weights", TEACHER_WEIGHTS,
#         "--train_steps", str(TRAIN_STEPS),
#         "--num_workers", "2",
#         "--tb_log_every", "10",
#         "--tb_eval_every", "10000",
#         "--save_every", "1000",
#     ]
#     if dataset == "mvtec_ad":
#         cmd += ["--mvtec_ad_path", dataset_root]
#     else:
#         cmd += ["--mvtec_loco_path", dataset_root]

#     if USE_PENALTY:
#         cmd += ["--imagenet_train_path", IMAGENET_TRAIN_PATH]
#     else:
#         cmd += ["--imagenet_train_path", "none"]

#     print("\nRUN:", " ".join(cmd))
#     subprocess.run(cmd, check=True)

# # ---- اجرا روی دیتاست 1: MVTec AD
# for obj in MVTEC_AD_OBJECTS:
#     run_one("mvtec_ad", obj, str(MVTEC_AD_ROOT))

# # ---- اجرا روی دیتاست 2: MVTec LOCO AD
# for obj in MVTEC_LOCO_OBJECTS:
#     run_one("mvtec_loco", obj, str(MVTEC_LOCO_ROOT))

# print("\n[DONE] training + inference finished. Outputs:", OUTPUT_DIR)

OUTPUT_DIR = Path("/content/outputs/efficientad_runs")
MVTEC_AD_ROOT = "/content/datasets/mvtec_anomaly_detection"
MVTEC_LOCO_ROOT = "/content/datasets/mvtec_loco_anomaly_detection"
IMAGENETTE_TRAIN = "/content/datasets/imagenette2-160/train"

# TRAIN_STEPS = 2000        # تست سریع
# MODEL_SIZE = "small"

TRAIN_STEPS = 7000        # تست سریع
MODEL_SIZE = "medium"

USE_PENALTY = True        # چون Imagenette آماده است

MVTEC_AD_OBJECTS = ["bottle"]
MVTEC_LOCO_OBJECTS = ["breakfast_box"]

# MVTec AD (bottle)
!python efficientad_tb.py \
  --dataset mvtec_ad --subdataset bottle \
  --mvtec_ad_path "{MVTEC_AD_ROOT}" \
  --output_dir "{OUTPUT_DIR}" \
  --model_size {MODEL_SIZE} \
  --weights "models/teacher_{MODEL_SIZE}.pth" \
  --imagenet_train_path "{IMAGENETTE_TRAIN}" \
  --train_steps {TRAIN_STEPS}

# MVTec LOCO (breakfast_box)
!python efficientad_tb.py \
  --dataset mvtec_loco --subdataset breakfast_box \
  --mvtec_loco_path "{MVTEC_LOCO_ROOT}" \
  --output_dir "{OUTPUT_DIR}" \
  --model_size {MODEL_SIZE} \
  --weights "models/teacher_{MODEL_SIZE}.pth" \
  --imagenet_train_path "{IMAGENETTE_TRAIN}" \
  --train_steps {TRAIN_STEPS}

"""لوکو سخت‌تره و ۲۰۰۰ استپ خیلی کمه

حداقل دو دیتاست :

MVTec AD (bottle)

MVTec LOCO (breakfast_box)

سنگین - محدودیت در اجرا :
"""

OUTPUT_DIR = Path("/content/outputs/efficientad_runs")
MVTEC_AD_ROOT = "/content/datasets/mvtec_anomaly_detection"
MVTEC_LOCO_ROOT = "/content/datasets/mvtec_loco_anomaly_detection"
IMAGENETTE_TRAIN = "/content/datasets/imagenette2-160/train"

TRAIN_STEPS=7000
MODEL_SIZE="medium"
USE_PENALTY = True        # چون Imagenette آماده است


MVTEC_AD_OBJECTS = ["bottle"]

# MVTec AD (bottle)
!python efficientad_tb.py \
  --dataset mvtec_ad --subdataset bottle \
  --mvtec_ad_path "{MVTEC_AD_ROOT}" \
  --output_dir "{OUTPUT_DIR}" \
  --model_size {MODEL_SIZE} \
  --weights "models/teacher_{MODEL_SIZE}.pth" \
  --imagenet_train_path "{IMAGENETTE_TRAIN}" \
  --train_steps {TRAIN_STEPS}

TRAIN_STEPS=70000
MODEL_SIZE="medium"
USE_PENALTY = True        # چون Imagenette آماده است

MVTEC_LOCO_OBJECTS = ["breakfast_box"]

!python efficientad_tb.py \
  --dataset mvtec_loco --subdataset breakfast_box \
  --mvtec_loco_path "{MVTEC_LOCO_ROOT}" \
  --output_dir "{OUTPUT_DIR}" \
  --model_size {MODEL_SIZE} \
  --weights "models/teacher_{MODEL_SIZE}.pth" \
  --imagenet_train_path "{IMAGENETTE_TRAIN}" \
  --train_steps {TRAIN_STEPS}

!find /content/outputs/efficientad_runs/trainings -name "*_final.pth" -maxdepth 6
!find /content/outputs/efficientad_runs/anomaly_maps -name "*.tiff" | head -n 20
!find /content/outputs/efficientad_runs/trainings -name "final_metrics.json" -print

!ls -la /content/outputs/efficientad_runs/trainings/mvtec_ad/bottle | head -n 50
!ls -la /content/outputs/efficientad_runs/trainings/mvtec_loco/breakfast_box | head -n 50
!find /content/outputs/efficientad_runs -name "*.tiff" | head -n 10

!find /content/outputs/efficientad_runs -maxdepth 5 -type d | head -n 80
!find /content/outputs/efficientad_runs -maxdepth 8 -type f -name "*.tiff" | head -n 20
!find /content/outputs/efficientad_runs -maxdepth 8 -type f -name "final_metrics.json" -print

"""## 8-"""

# Commented out IPython magic to ensure Python compatibility.

# =======================================================
# 8) TensorBoard (Train & Test)
# =======================================================
# %load_ext tensorboard
TB_ROOT = "/content/outputs/efficientad_runs/trainings"
# %tensorboard --logdir {TB_ROOT}

!find /content/outputs/efficientad_runs -maxdepth 8 -name "final_metrics.json" -print

"""## 9-"""

# =======================================================
# 9) Collect metrics + weights report (CSV)
# =======================================================
import pandas as pd
from pathlib import Path
import json

TRAININGS_ROOT = OUTPUT_DIR/"trainings"
rows = []
weights_rows = []

for dataset in ["mvtec_ad", "mvtec_loco"]:
    ds_dir = TRAININGS_ROOT/dataset
    if not ds_dir.exists():
        continue
    for sub in sorted([p.name for p in ds_dir.iterdir() if p.is_dir()]):
        metrics_path = ds_dir/sub/"final_metrics.json"
        if metrics_path.exists():
            m = json.loads(metrics_path.read_text())
        else:
            m = {"dataset": dataset, "subdataset": sub}
        rows.append(m)

        # weights
        w_teacher = ds_dir/sub/"teacher_final.pth"
        w_student = ds_dir/sub/"student_final.pth"
        w_ae = ds_dir/sub/"autoencoder_final.pth"
        for wpath in [w_teacher, w_student, w_ae]:
            if wpath.exists():
                weights_rows.append({
                    "dataset": dataset,
                    "subdataset": sub,
                    "weight_file": wpath.name,
                    "path": str(wpath),
                    "size_mb": round(wpath.stat().st_size/1e6, 2),
                })

metrics_df = pd.DataFrame(rows).sort_values(["dataset","subdataset"])
weights_df = pd.DataFrame(weights_rows).sort_values(["dataset","subdataset","weight_file"])

metrics_csv = OUTPUT_DIR/"metrics_summary.csv"
weights_csv = OUTPUT_DIR/"weights_report.csv"

metrics_df.to_csv(metrics_csv, index=False)
weights_df.to_csv(weights_csv, index=False)

print("Saved:", metrics_csv, weights_csv)
display(metrics_df)
display(weights_df.head(20))

!pip -q install scikit-image

from pathlib import Path
OUTPUT_DIR = Path("/content/outputs/efficientad_runs")
MVTEC_AD_ROOT = "/content/datasets/mvtec_anomaly_detection"
MVTEC_LOCO_ROOT = "/content/datasets/mvtec_loco_anomaly_detection"
# TRAIN_STEPS = 7000

# =======================================================
# 9.5) Custom pixel metrics (Pixel AUROC + AU-PRO@0.3)
#      بدون نیاز به اسکریپت‌های ارزیابی خارجی
#      - برای Train/Test در TensorBoard هم ثبت می‌کند.
# =======================================================
import numpy as np
import pandas as pd
from pathlib import Path
from PIL import Image
import tifffile
from sklearn.metrics import roc_auc_score
from skimage.measure import label
from torch.utils.tensorboard import SummaryWriter
import json, math

def _load_mask(mask_path: Path, target_shape):
    if mask_path.exists():
        m = np.array(Image.open(mask_path).convert("L"), dtype=np.uint8)
        m = (m > 0).astype(np.uint8)
        if m.shape != target_shape:
            m_img = Image.fromarray(m * 255).resize((target_shape[1], target_shape[0]), resample=Image.NEAREST)
            m = (np.array(m_img) > 0).astype(np.uint8)
        return m
    return np.zeros(target_shape, dtype=np.uint8)

def pixel_auroc_and_pro(pred_maps, gt_masks, pro_limit=0.3, n_thresh=200):
    # Pixel AUROC
    y_true = np.concatenate([m.flatten() for m in gt_masks]).astype(np.uint8)
    y_score = np.concatenate([p.flatten() for p in pred_maps]).astype(np.float32)

    if len(np.unique(y_true)) < 2:
        pixel_auc = np.nan
    else:
        pixel_auc = float(roc_auc_score(y_true, y_score))

    # AU-PRO@limit
    s_min, s_max = float(y_score.min()), float(y_score.max())
    if s_max - s_min < 1e-12:
        return pixel_auc, np.nan
    pred_maps_n = [(p - s_min) / (s_max - s_min + 1e-12) for p in pred_maps]

    thresholds = np.linspace(0.0, 1.0, n_thresh, dtype=np.float32)
    fprs, pros = [], []

    for thr in thresholds:
        pro_vals = []
        fp = 0
        tn = 0

        for p, gt in zip(pred_maps_n, gt_masks):
            pred_bin = (p >= thr).astype(np.uint8)

            bg = (gt == 0)
            fp += int((pred_bin[bg] == 1).sum())
            tn += int((pred_bin[bg] == 0).sum())

            if gt.sum() == 0:
                continue

            cc = label(gt, connectivity=1)
            for rid in range(1, cc.max() + 1):
                region = (cc == rid)
                region_area = int(region.sum())
                if region_area == 0:
                    continue
                inter = int((pred_bin[region] == 1).sum())
                pro_vals.append(inter / (region_area + 1e-12))

        fpr = fp / (fp + tn + 1e-12)
        pro = float(np.mean(pro_vals)) if len(pro_vals) else 0.0

        fprs.append(fpr)
        pros.append(pro)

    fprs = np.array(fprs, dtype=np.float32)
    pros = np.array(pros, dtype=np.float32)

    order = np.argsort(fprs)
    fprs = fprs[order]
    pros = pros[order]

    m = fprs <= pro_limit
    if m.sum() < 2:
        au_pro = np.nan
    else:
        area = np.trapz(pros[m], fprs[m])
        au_pro = float(area / (pro_limit + 1e-12))

    return pixel_auc, au_pro

def evaluate_one(dataset_root: Path, anomaly_maps_root: Path, subdataset: str):
    test_dir = dataset_root / subdataset / "test"
    gt_dir = dataset_root / subdataset / "ground_truth"

    pred_maps, gt_masks = [], []

    for defect in sorted([p.name for p in test_dir.iterdir() if p.is_dir()]):
        img_dir = test_dir / defect
        for img_path in sorted(img_dir.glob("*.*")):
            img_stem = img_path.stem
            pred_path = anomaly_maps_root / defect / f"{img_stem}.tiff"
            if not pred_path.exists():
                alt = anomaly_maps_root / defect / f"{img_stem}.tif"
                if alt.exists():
                    pred_path = alt
                else:
                    continue

            pred = tifffile.imread(pred_path.as_posix()).astype(np.float32)
            if pred.ndim != 2:
                pred = pred.squeeze()

            if defect == "good":
                gt = np.zeros(pred.shape, dtype=np.uint8)
            else:
                mask_path = gt_dir / defect / f"{img_stem}_mask.png"
                gt = _load_mask(mask_path, pred.shape)

            pred_maps.append(pred)
            gt_masks.append(gt)

    if len(pred_maps) == 0:
        return {"pixel_auroc": np.nan, "au_pro_0.3": np.nan, "n_images": 0}

    pixel_auc, au_pro = pixel_auroc_and_pro(pred_maps, gt_masks, pro_limit=0.3, n_thresh=200)
    return {"pixel_auroc": pixel_auc, "au_pro_0.3": au_pro, "n_images": len(pred_maps)}

TRAININGS_ROOT = OUTPUT_DIR / "trainings"
ANOMALY_ROOT = OUTPUT_DIR / "anomaly_maps"

extra_rows = []
for dataset in ["mvtec_ad", "mvtec_loco"]:
    ds_dir = TRAININGS_ROOT / dataset
    if not ds_dir.exists():
        continue

    dataset_root = Path(MVTEC_AD_ROOT) if dataset == "mvtec_ad" else Path(MVTEC_LOCO_ROOT)

    for sub in sorted([p.name for p in ds_dir.iterdir() if p.is_dir()]):
        maps_root = ANOMALY_ROOT / dataset / sub / "test"
        res = evaluate_one(dataset_root, maps_root, sub)

        tb_dir = ds_dir / sub / "tensorboard"
        writer = SummaryWriter(log_dir=str(tb_dir))
        if not (res["pixel_auroc"] is None or math.isnan(res["pixel_auroc"])):
            writer.add_scalar("test/pixel_auroc_custom", res["pixel_auroc"], TRAIN_STEPS)
        if not (res["au_pro_0.3"] is None or math.isnan(res["au_pro_0.3"])):
            writer.add_scalar("test/au_pro_0.3_custom", res["au_pro_0.3"], TRAIN_STEPS)
        writer.flush()
        writer.close()

        extra_rows.append({"dataset": dataset, "subdataset": sub, **res})

extra_df = pd.DataFrame(extra_rows).sort_values(["dataset", "subdataset"])
extra_csv = OUTPUT_DIR / "pixel_metrics_custom.csv"
extra_df.to_csv(extra_csv, index=False)
print("Saved:", extra_csv)
display(extra_df)

"""“Pixel metrics are computed in a memory-safe manner using random pixel sampling (up to 2M pixels) and AU-PRO computed on a representative subset of images (up to 120) with 50 thresholds.”"""

# =======================================================
# 9.5) Memory-safe pixel metrics (Pixel AUROC + AU-PRO@0.3)
#      - streaming / sampling to avoid RAM crash
# =======================================================
import numpy as np
import pandas as pd
from pathlib import Path
from PIL import Image
import tifffile
from sklearn.metrics import roc_auc_score
from skimage.measure import label
from torch.utils.tensorboard import SummaryWriter
import math, random

# --- make sure these exist
OUTPUT_DIR = Path("/content/outputs/efficientad_runs")
MVTEC_AD_ROOT = Path("/content/datasets/mvtec_anomaly_detection")
MVTEC_LOCO_ROOT = Path("/content/datasets/mvtec_loco_anomaly_detection")
TRAIN_STEPS = 2000  # همون مقدار اجرای فعلی

TRAININGS_ROOT = OUTPUT_DIR / "trainings"
ANOMALY_ROOT = OUTPUT_DIR / "anomaly_maps"

def _load_mask(mask_path: Path, target_shape):
    if mask_path.exists():
        m = np.array(Image.open(mask_path).convert("L"), dtype=np.uint8)
        m = (m > 0).astype(np.uint8)
        if m.shape != target_shape:
            m_img = Image.fromarray(m * 255).resize((target_shape[1], target_shape[0]), resample=Image.NEAREST)
            m = (np.array(m_img) > 0).astype(np.uint8)
        return m
    return np.zeros(target_shape, dtype=np.uint8)

def iter_samples(dataset_root: Path, anomaly_maps_root: Path, subdataset: str):
    """Yield (pred_map, gt_mask) one by one to keep RAM low."""
    test_dir = dataset_root / subdataset / "test"
    gt_dir = dataset_root / subdataset / "ground_truth"

    for defect in sorted([p.name for p in test_dir.iterdir() if p.is_dir()]):
        img_dir = test_dir / defect
        for img_path in sorted(img_dir.glob("*.*")):
            stem = img_path.stem
            pred_path = anomaly_maps_root / defect / f"{stem}.tiff"
            if not pred_path.exists():
                alt = anomaly_maps_root / defect / f"{stem}.tif"
                if alt.exists():
                    pred_path = alt
                else:
                    continue

            pred = tifffile.imread(pred_path.as_posix()).astype(np.float32)
            if pred.ndim != 2:
                pred = pred.squeeze()

            if defect == "good":
                gt = np.zeros(pred.shape, dtype=np.uint8)
            else:
                mask_path = gt_dir / defect / f"{stem}_mask.png"
                gt = _load_mask(mask_path, pred.shape)

            yield pred, gt, defect

def pixel_auroc_streaming(dataset_root: Path, anomaly_maps_root: Path, subdataset: str,
                          max_pixels=2_000_000, seed=42):
    """
    Compute Pixel AUROC with random pixel sampling to avoid huge RAM.
    max_pixels: maximum total pixels sampled across the dataset.
    """
    rng = np.random.default_rng(seed)
    y_true_chunks = []
    y_score_chunks = []
    total = 0
    n_images = 0

    for pred, gt, _ in iter_samples(dataset_root, anomaly_maps_root, subdataset):
        n_images += 1
        flat_pred = pred.reshape(-1)
        flat_gt = gt.reshape(-1)

        # sample pixels from this image
        remaining = max_pixels - total
        if remaining <= 0:
            break

        take = min(len(flat_pred), max(5000, remaining // 10))  # حداقل 5k از هر تصویر
        idx = rng.choice(len(flat_pred), size=take, replace=False)

        y_score_chunks.append(flat_pred[idx].astype(np.float32))
        y_true_chunks.append(flat_gt[idx].astype(np.uint8))
        total += take

    if n_images == 0:
        return np.nan, 0

    y_true = np.concatenate(y_true_chunks)
    y_score = np.concatenate(y_score_chunks)

    if len(np.unique(y_true)) < 2:
        return np.nan, n_images

    return float(roc_auc_score(y_true, y_score)), n_images

def au_pro_streaming(dataset_root: Path, anomaly_maps_root: Path, subdataset: str,
                     pro_limit=0.3, n_thresh=50, max_images=120, seed=42):
    """
    Memory-safe AU-PRO:
    - Uses subset of images (max_images)
    - Uses fewer thresholds (n_thresh)
    """
    rng = np.random.default_rng(seed)

    # collect list of available samples (paths only, not arrays)
    # (کم‌هزینه چون فقط مسیرها را نگه می‌داریم)
    samples = []
    test_dir = dataset_root / subdataset / "test"
    for defect in sorted([p.name for p in test_dir.iterdir() if p.is_dir()]):
        img_dir = test_dir / defect
        for img_path in sorted(img_dir.glob("*.*")):
            stem = img_path.stem
            pred_path = anomaly_maps_root / defect / f"{stem}.tiff"
            if not pred_path.exists():
                alt = anomaly_maps_root / defect / f"{stem}.tif"
                if alt.exists():
                    pred_path = alt
                else:
                    continue
            samples.append((pred_path, defect, stem))

    if len(samples) == 0:
        return np.nan, 0

    # subsample images
    if len(samples) > max_images:
        idx = rng.choice(len(samples), size=max_images, replace=False)
        samples = [samples[i] for i in idx]

    # find global min/max on subset for normalization
    mins, maxs = [], []
    for pred_path, _, _ in samples:
        pred = tifffile.imread(pred_path.as_posix()).astype(np.float32)
        if pred.ndim != 2:
            pred = pred.squeeze()
        mins.append(float(pred.min()))
        maxs.append(float(pred.max()))
    s_min, s_max = float(np.min(mins)), float(np.max(maxs))
    if s_max - s_min < 1e-12:
        return np.nan, len(samples)

    thresholds = np.linspace(0.0, 1.0, n_thresh, dtype=np.float32)
    fprs, pros = [], []

    gt_dir = dataset_root / subdataset / "ground_truth"

    for thr in thresholds:
        pro_vals = []
        fp = 0
        tn = 0

        for pred_path, defect, stem in samples:
            pred = tifffile.imread(pred_path.as_posix()).astype(np.float32)
            if pred.ndim != 2:
                pred = pred.squeeze()
            p = (pred - s_min) / (s_max - s_min + 1e-12)
            pred_bin = (p >= thr).astype(np.uint8)

            if defect == "good":
                gt = np.zeros(pred_bin.shape, dtype=np.uint8)
            else:
                mask_path = gt_dir / defect / f"{stem}_mask.png"
                gt = _load_mask(mask_path, pred_bin.shape)

            bg = (gt == 0)
            fp += int((pred_bin[bg] == 1).sum())
            tn += int((pred_bin[bg] == 0).sum())

            if gt.sum() == 0:
                continue

            cc = label(gt, connectivity=1)
            for rid in range(1, cc.max() + 1):
                region = (cc == rid)
                area = int(region.sum())
                if area == 0:
                    continue
                inter = int((pred_bin[region] == 1).sum())
                pro_vals.append(inter / (area + 1e-12))

        fpr = fp / (fp + tn + 1e-12)
        pro = float(np.mean(pro_vals)) if len(pro_vals) else 0.0
        fprs.append(fpr)
        pros.append(pro)

    fprs = np.array(fprs, dtype=np.float32)
    pros = np.array(pros, dtype=np.float32)

    order = np.argsort(fprs)
    fprs = fprs[order]
    pros = pros[order]

    m = fprs <= pro_limit
    if m.sum() < 2:
        return np.nan, len(samples)

    area = np.trapz(pros[m], fprs[m])
    au_pro = float(area / (pro_limit + 1e-12))
    return au_pro, len(samples)

def evaluate_one(dataset_root: Path, anomaly_maps_root: Path, subdataset: str):
    pixel_auc, n_img_pix = pixel_auroc_streaming(dataset_root, anomaly_maps_root, subdataset,
                                                 max_pixels=2_000_000, seed=42)
    au_pro, n_img_pro = au_pro_streaming(dataset_root, anomaly_maps_root, subdataset,
                                         pro_limit=0.3, n_thresh=50, max_images=120, seed=42)
    return {
        "pixel_auroc_sampled": pixel_auc,
        "au_pro_0.3_sampled": au_pro,
        "n_images_pixel": int(n_img_pix),
        "n_images_pro": int(n_img_pro),
    }

extra_rows = []
for dataset in ["mvtec_ad", "mvtec_loco"]:
    ds_dir = TRAININGS_ROOT / dataset
    if not ds_dir.exists():
        continue

    dataset_root = MVTEC_AD_ROOT if dataset == "mvtec_ad" else MVTEC_LOCO_ROOT

    for sub in sorted([p.name for p in ds_dir.iterdir() if p.is_dir()]):
        maps_root = ANOMALY_ROOT / dataset / sub / "test"
        res = evaluate_one(dataset_root, maps_root, sub)

        # log to tensorboard
        tb_dir = ds_dir / sub / "tensorboard"
        writer = SummaryWriter(log_dir=str(tb_dir))
        if not (res["pixel_auroc_sampled"] is None or math.isnan(res["pixel_auroc_sampled"])):
            writer.add_scalar("test/pixel_auroc_sampled", res["pixel_auroc_sampled"], TRAIN_STEPS)
        if not (res["au_pro_0.3_sampled"] is None or math.isnan(res["au_pro_0.3_sampled"])):
            writer.add_scalar("test/au_pro_0.3_sampled", res["au_pro_0.3_sampled"], TRAIN_STEPS)
        writer.flush()
        writer.close()

        extra_rows.append({"dataset": dataset, "subdataset": sub, **res})

extra_df = pd.DataFrame(extra_rows).sort_values(["dataset", "subdataset"])
extra_csv = OUTPUT_DIR / "pixel_metrics_custom_sampled.csv"
extra_df.to_csv(extra_csv, index=False)
print("✅ Saved:", extra_csv)
display(extra_df)

"""خیلی وقت‌ها در نمونه‌برداری رندوم پیکسل‌ها ممکنه تمام پیکسل‌های انتخاب‌شده “نرمال” باشند (کلاس 0)"""

!cat /content/outputs/efficientad_runs/pixel_metrics_custom.csv
!cat /content/outputs/efficientad_runs/pixel_metrics_custom_sampled.csv

# =======================================================
# 9.5) Reliable + RAM-safe Pixel metrics (Pixel AUROC + AU-PRO@0.3)
#      - Pixel metrics computed ONLY on images that have GT masks
#      - Pixel AUROC via histogram (streaming, no huge concat)
#      - AU-PRO@0.3 via sampled images + fewer thresholds (stable)
# =======================================================
import numpy as np
import pandas as pd
from pathlib import Path
from PIL import Image
import tifffile
from skimage.measure import label
from sklearn.metrics import roc_auc_score
from torch.utils.tensorboard import SummaryWriter
import math

# ---- make sure these exist from your earlier cells
OUTPUT_DIR = Path("/content/outputs/efficientad_runs")
MVTEC_AD_ROOT = Path("/content/datasets/mvtec_anomaly_detection")
MVTEC_LOCO_ROOT = Path("/content/datasets/mvtec_loco_anomaly_detection")
TRAIN_STEPS = int(TRAIN_STEPS) if "TRAIN_STEPS" in globals() else 7000

TRAININGS_ROOT = OUTPUT_DIR / "trainings"
ANOMALY_ROOT   = OUTPUT_DIR / "anomaly_maps"

def _load_mask_any(gt_dir: Path, defect: str, stem: str, target_shape):
    """
    Try multiple mask naming conventions (AD + LOCO).
    Returns: mask (0/1) or None if no mask exists.
    """
    if defect == "good":
        return None

    candidates = [
        gt_dir / defect / f"{stem}_mask.png",
        gt_dir / defect / f"{stem}.png",
        gt_dir / defect / f"{stem}_mask.tif",
        gt_dir / defect / f"{stem}.tif",
        gt_dir / defect / f"{stem}_mask.tiff",
        gt_dir / defect / f"{stem}.tiff",
    ]
    for p in candidates:
        if p.exists():
            m = np.array(Image.open(p).convert("L"), dtype=np.uint8)
            m = (m > 0).astype(np.uint8)
            if m.shape != target_shape:
                m_img = Image.fromarray(m * 255).resize((target_shape[1], target_shape[0]), resample=Image.NEAREST)
                m = (np.array(m_img) > 0).astype(np.uint8)
            return m
    return None

def iter_pred_gt(dataset_root: Path, maps_root: Path, subdataset: str):
    """
    Yields (defect, stem, pred_map_float32, gt_mask_or_None)
    """
    test_dir = dataset_root / subdataset / "test"
    gt_dir   = dataset_root / subdataset / "ground_truth"

    for defect_dir in sorted([p for p in test_dir.iterdir() if p.is_dir()]):
        defect = defect_dir.name
        for img_path in sorted(defect_dir.glob("*")):
            if not img_path.is_file():
                continue
            stem = img_path.stem
            pred_path = maps_root / defect / f"{stem}.tiff"
            if not pred_path.exists():
                alt = maps_root / defect / f"{stem}.tif"
                if alt.exists():
                    pred_path = alt
                else:
                    continue

            pred = tifffile.imread(pred_path.as_posix()).astype(np.float32)
            if pred.ndim != 2:
                pred = pred.squeeze()

            gt = _load_mask_any(gt_dir, defect, stem, pred.shape)
            yield defect, stem, pred, gt

def image_auroc_from_maps(dataset_root: Path, maps_root: Path, subdataset: str):
    y_true, y_score = [], []
    for defect, stem, pred, gt in iter_pred_gt(dataset_root, maps_root, subdataset):
        y_true.append(0 if defect=="good" else 1)
        y_score.append(float(pred.max()))
    if len(set(y_true)) < 2:
        return np.nan, len(y_true)
    return float(roc_auc_score(y_true, y_score)), len(y_true)

def pixel_auroc_histogram(dataset_root: Path, maps_root: Path, subdataset: str, bins=4096):
    """
    Pixel AUROC using histogram accumulation (streaming).
    Computed ONLY on images with available GT mask.
    """
    smin, smax = None, None
    n_used_imgs = 0
    n_pos = 0
    n_neg = 0

    # pass 1: min/max + counts on GT-available images
    for defect, stem, pred, gt in iter_pred_gt(dataset_root, maps_root, subdataset):
        if gt is None:
            continue
        n_used_imgs += 1
        vmin, vmax = float(pred.min()), float(pred.max())
        smin = vmin if smin is None else min(smin, vmin)
        smax = vmax if smax is None else max(smax, vmax)
        n_pos += int((gt==1).sum())
        n_neg += int((gt==0).sum())

    if n_used_imgs == 0 or smin is None or (smax - smin) < 1e-12 or n_pos == 0 or n_neg == 0:
        return np.nan, n_used_imgs, n_pos, n_neg

    pos_hist = np.zeros(bins, dtype=np.int64)
    neg_hist = np.zeros(bins, dtype=np.int64)

    # pass 2: fill hist
    for defect, stem, pred, gt in iter_pred_gt(dataset_root, maps_root, subdataset):
        if gt is None:
            continue
        p = (pred - smin) / (smax - smin + 1e-12)
        p = np.clip(p, 0.0, 1.0)
        idx = np.minimum((p * (bins-1)).astype(np.int64), bins-1)

        pos_idx = idx[gt==1]
        neg_idx = idx[gt==0]
        if pos_idx.size:
            pos_hist += np.bincount(pos_idx, minlength=bins)
        if neg_idx.size:
            neg_hist += np.bincount(neg_idx, minlength=bins)

    pos_total = pos_hist.sum()
    neg_total = neg_hist.sum()
    if pos_total == 0 or neg_total == 0:
        return np.nan, n_used_imgs, int(pos_total), int(neg_total)

    # threshold from high to low
    tpr = np.cumsum(pos_hist[::-1]) / (pos_total + 1e-12)
    fpr = np.cumsum(neg_hist[::-1]) / (neg_total + 1e-12)

    auc = float(np.trapz(tpr, fpr))
    return auc, n_used_imgs, int(pos_total), int(neg_total)

def au_pro_03_sampled(dataset_root: Path, maps_root: Path, subdataset: str,
                      pro_limit=0.3, n_thresh=64, max_images=200, seed=42):
    """
    AU-PRO@0.3 computed on a subset of GT-available defect images (memory-safe).
    """
    rng = np.random.default_rng(seed)
    dataset_root = Path(dataset_root)
    maps_root = Path(maps_root)

    test_dir = dataset_root / subdataset / "test"
    gt_dir   = dataset_root / subdataset / "ground_truth"

    samples = []
    for defect_dir in sorted([p for p in test_dir.iterdir() if p.is_dir()]):
        defect = defect_dir.name
        if defect == "good":
            continue
        for img_path in sorted(defect_dir.glob("*")):
            if not img_path.is_file():
                continue
            stem = img_path.stem
            # must have mask
            if not any([
                (gt_dir/defect/f"{stem}_mask.png").exists(),
                (gt_dir/defect/f"{stem}.png").exists(),
                (gt_dir/defect/f"{stem}_mask.tif").exists(),
                (gt_dir/defect/f"{stem}.tif").exists(),
                (gt_dir/defect/f"{stem}_mask.tiff").exists(),
                (gt_dir/defect/f"{stem}.tiff").exists(),
            ]):
                continue
            pred_path = maps_root / defect / f"{stem}.tiff"
            if not pred_path.exists():
                alt = maps_root / defect / f"{stem}.tif"
                if alt.exists(): pred_path = alt
                else: continue
            samples.append((defect, stem, pred_path))

    if len(samples) == 0:
        return np.nan, 0

    if len(samples) > max_images:
        idx = rng.choice(len(samples), size=max_images, replace=False)
        samples = [samples[i] for i in idx]

    # global min/max on subset
    mins, maxs = [], []
    for defect, stem, pred_path in samples:
        pred = tifffile.imread(pred_path.as_posix()).astype(np.float32)
        if pred.ndim != 2: pred = pred.squeeze()
        mins.append(float(pred.min())); maxs.append(float(pred.max()))
    smin, smax = float(np.min(mins)), float(np.max(maxs))
    if (smax - smin) < 1e-12:
        return np.nan, len(samples)

    thresholds = np.linspace(0.0, 1.0, n_thresh, dtype=np.float32)
    fprs, pros = [], []

    for thr in thresholds:
        pro_vals = []
        fp = 0
        tn = 0

        for defect, stem, pred_path in samples:
            pred = tifffile.imread(pred_path.as_posix()).astype(np.float32)
            if pred.ndim != 2: pred = pred.squeeze()

            p = (pred - smin) / (smax - smin + 1e-12)
            p = np.clip(p, 0.0, 1.0)
            pb = (p >= thr).astype(np.uint8)

            gt = _load_mask_any(gt_dir, defect, stem, pb.shape)
            if gt is None:
                continue

            bg = (gt == 0)
            fp += int((pb[bg] == 1).sum())
            tn += int((pb[bg] == 0).sum())

            cc = label(gt, connectivity=1)
            for rid in range(1, cc.max()+1):
                region = (cc == rid)
                area = int(region.sum())
                if area == 0:
                    continue
                inter = int((pb[region] == 1).sum())
                pro_vals.append(inter / (area + 1e-12))

        fpr = fp / (fp + tn + 1e-12)
        pro = float(np.mean(pro_vals)) if len(pro_vals) else 0.0
        fprs.append(fpr)
        pros.append(pro)

    fprs = np.array(fprs, dtype=np.float32)
    pros = np.array(pros, dtype=np.float32)
    order = np.argsort(fprs)
    fprs = fprs[order]
    pros = pros[order]

    m = fprs <= pro_limit
    if m.sum() < 2:
        return np.nan, len(samples)

    area = np.trapz(pros[m], fprs[m])
    au_pro = float(area / (pro_limit + 1e-12))
    return au_pro, len(samples)

# ---- main evaluate
extra_rows = []
for dataset in ["mvtec_ad", "mvtec_loco"]:
    ds_dir = TRAININGS_ROOT / dataset
    if not ds_dir.exists():
        continue

    dataset_root = MVTEC_AD_ROOT if dataset == "mvtec_ad" else MVTEC_LOCO_ROOT

    for sub in sorted([p.name for p in ds_dir.iterdir() if p.is_dir()]):
        maps_root = ANOMALY_ROOT / dataset / sub / "test"

        img_auc, n_img = image_auroc_from_maps(dataset_root, maps_root, sub)
        pix_auc, n_used, n_pos, n_neg = pixel_auroc_histogram(dataset_root, maps_root, sub, bins=4096)
        pro, n_pro = au_pro_03_sampled(dataset_root, maps_root, sub, pro_limit=0.3, n_thresh=64, max_images=200)

        note = ("Pixel metrics computed ONLY on images that have GT masks. "
                "If a dataset has missing pixel GT (common in LOCO logical anomalies), pixel AUROC may be NaN.")

        # log to tensorboard
        tb_dir = ds_dir / sub / "tensorboard"
        writer = SummaryWriter(log_dir=str(tb_dir))
        if not (img_auc is None or math.isnan(img_auc)):
            writer.add_scalar("test/image_auc_recomputed", img_auc, TRAIN_STEPS)
        if not (pix_auc is None or math.isnan(pix_auc)):
            writer.add_scalar("test/pixel_auroc_hist", pix_auc, TRAIN_STEPS)
        if not (pro is None or math.isnan(pro)):
            writer.add_scalar("test/au_pro_0.3", pro, TRAIN_STEPS)
        writer.add_text("test/pixel_metrics_note", note, TRAIN_STEPS)
        writer.flush()
        writer.close()

        extra_rows.append({
            "dataset": dataset,
            "subdataset": sub,
            "image_auc_recomputed": img_auc,
            "pixel_auroc_hist": pix_auc,
            "au_pro_0.3": pro,
            "n_test_images": int(n_img),
            "n_images_with_gt_used_for_pixel": int(n_used),
            "n_pos_pixels": int(n_pos),
            "n_neg_pixels": int(n_neg),
            "n_images_used_for_pro": int(n_pro),
            "note": note
        })

extra_df = pd.DataFrame(extra_rows).sort_values(["dataset", "subdataset"])
extra_csv = OUTPUT_DIR / "pixel_metrics_reliable.csv"
extra_df.to_csv(extra_csv, index=False)
print("✅ Saved:", extra_csv)
display(extra_df)

# =======================================================
# 9.5) Proper & RAM-safe Pixel metrics (Exact streaming)
#      Pixel AUROC + AU-PRO@0.3 for MVTec AD + LOCO
# =======================================================
import numpy as np
import pandas as pd
from pathlib import Path
from PIL import Image
import tifffile
from sklearn.metrics import roc_auc_score
from skimage.measure import label
from torch.utils.tensorboard import SummaryWriter
import math, glob

OUTPUT_DIR = Path("/content/outputs/efficientad_runs")
MVTEC_AD_ROOT = Path("/content/datasets/mvtec_anomaly_detection")
MVTEC_LOCO_ROOT = Path("/content/datasets/mvtec_loco_anomaly_detection")
TRAIN_STEPS = int(globals().get("TRAIN_STEPS", 70000))  # اگر ست کرده‌ای استفاده می‌کند

TRAININGS_ROOT = OUTPUT_DIR / "trainings"
ANOMALY_ROOT = OUTPUT_DIR / "anomaly_maps"

def load_mask_any(mask_candidates, target_shape):
    """Load first existing mask path from candidates; resize to target if needed."""
    for mp in mask_candidates:
        mp = Path(mp)
        if mp.exists():
            m = np.array(Image.open(mp).convert("L"), dtype=np.uint8)
            m = (m > 0).astype(np.uint8)
            if m.shape != target_shape:
                m_img = Image.fromarray(m * 255).resize((target_shape[1], target_shape[0]), resample=Image.NEAREST)
                m = (np.array(m_img) > 0).astype(np.uint8)
            return m
    return np.zeros(target_shape, dtype=np.uint8)

def iter_pred_gt(dataset_root: Path, anomaly_maps_root: Path, subdataset: str, dataset_kind: str):
    """
    Yield (pred_map, gt_mask) one by one.
    dataset_kind: "mvtec_ad" or "mvtec_loco"
    """
    test_dir = dataset_root / subdataset / "test"
    gt_dir = dataset_root / subdataset / "ground_truth"

    for defect_dir in sorted([p for p in test_dir.iterdir() if p.is_dir()]):
        defect = defect_dir.name
        for img_path in sorted(defect_dir.glob("*.*")):
            stem = img_path.stem

            pred_path = anomaly_maps_root / defect / f"{stem}.tiff"
            if not pred_path.exists():
                alt = anomaly_maps_root / defect / f"{stem}.tif"
                if alt.exists():
                    pred_path = alt
                else:
                    continue

            pred = tifffile.imread(pred_path.as_posix()).astype(np.float32)
            if pred.ndim != 2:
                pred = pred.squeeze()

            if defect == "good":
                gt = np.zeros(pred.shape, dtype=np.uint8)
            else:
                # --- MVTec AD: <stem>_mask.png
                # --- LOCO: usually <stem>.png (and sometimes also *_mask.png) -> so we search both safely
                if dataset_kind == "mvtec_ad":
                    cands = [gt_dir / defect / f"{stem}_mask.png"]
                else:
                    cands = [
                        gt_dir / defect / f"{stem}.png",
                        gt_dir / defect / f"{stem}_mask.png",
                    ]
                    # extra robust: any png that starts with stem
                    cands += list((gt_dir / defect).glob(f"{stem}*.png"))

                gt = load_mask_any(cands, pred.shape)

            yield pred, gt

def pixel_auroc_stream(dataset_root: Path, anomaly_maps_root: Path, subdataset: str, dataset_kind: str,
                       max_pixels=3_000_000, seed=42):
    """
    Pixel AUROC with bounded RAM: random pixel sampling across images.
    This is standard & defensible when full pixel set is huge.
    """
    rng = np.random.default_rng(seed)
    y_true_chunks, y_score_chunks = [], []
    total = 0
    n_images = 0

    for pred, gt in iter_pred_gt(dataset_root, anomaly_maps_root, subdataset, dataset_kind):
        n_images += 1
        flat_pred = pred.reshape(-1)
        flat_gt = gt.reshape(-1)

        remaining = max_pixels - total
        if remaining <= 0:
            break

        take = min(len(flat_pred), max(20000, remaining // 8))  # حداقل 20k از هر تصویر
        idx = rng.choice(len(flat_pred), size=take, replace=False)

        y_score_chunks.append(flat_pred[idx].astype(np.float32))
        y_true_chunks.append(flat_gt[idx].astype(np.uint8))
        total += take

    if n_images == 0:
        return np.nan, 0

    y_true = np.concatenate(y_true_chunks)
    y_score = np.concatenate(y_score_chunks)

    if len(np.unique(y_true)) < 2:
        return np.nan, n_images

    return float(roc_auc_score(y_true, y_score)), n_images

def au_pro_stream_full(dataset_root: Path, anomaly_maps_root: Path, subdataset: str, dataset_kind: str,
                       pro_limit=0.3, n_thresh=100):
    """
    AU-PRO streaming (no RAM explosion):
    - 1) scan min/max
    - 2) thresholds loop and compute FPR/PRO sequentially
    """
    # --- 1) global min/max scan
    mins, maxs = [], []
    pairs = []
    for pred, gt in iter_pred_gt(dataset_root, anomaly_maps_root, subdataset, dataset_kind):
        mins.append(float(pred.min()))
        maxs.append(float(pred.max()))
        pairs.append((pred, gt))  # NOTE: still could be heavy if we keep all

    # To avoid keeping pairs in RAM, we re-iterate instead of storing.
    # So we won't use `pairs` at all:
    del pairs

    if len(mins) == 0:
        return np.nan, 0

    s_min, s_max = float(np.min(mins)), float(np.max(maxs))
    if s_max - s_min < 1e-12:
        return np.nan, len(mins)

    thresholds = np.linspace(0.0, 1.0, n_thresh, dtype=np.float32)
    fprs, pros = [], []

    # --- 2) compute curves
    n_images = 0
    for thr in thresholds:
        fp = 0
        tn = 0
        pro_vals = []

        # re-iterate without storing
        for pred, gt in iter_pred_gt(dataset_root, anomaly_maps_root, subdataset, dataset_kind):
            n_images += 1
            p = (pred - s_min) / (s_max - s_min + 1e-12)
            pred_bin = (p >= thr).astype(np.uint8)

            bg = (gt == 0)
            fp += int((pred_bin[bg] == 1).sum())
            tn += int((pred_bin[bg] == 0).sum())

            if gt.sum() == 0:
                continue

            cc = label(gt, connectivity=1)
            for rid in range(1, cc.max() + 1):
                region = (cc == rid)
                area = int(region.sum())
                if area == 0:
                    continue
                inter = int((pred_bin[region] == 1).sum())
                pro_vals.append(inter / (area + 1e-12))

        fpr = fp / (fp + tn + 1e-12)
        pro = float(np.mean(pro_vals)) if len(pro_vals) else 0.0
        fprs.append(fpr)
        pros.append(pro)

    fprs = np.array(fprs, dtype=np.float32)
    pros = np.array(pros, dtype=np.float32)

    order = np.argsort(fprs)
    fprs = fprs[order]
    pros = pros[order]

    m = fprs <= pro_limit
    if m.sum() < 2:
        return np.nan, len(mins)

    area = np.trapz(pros[m], fprs[m])
    au_pro = float(area / (pro_limit + 1e-12))
    return au_pro, len(mins)

rows = []
for dataset in ["mvtec_ad", "mvtec_loco"]:
    ds_dir = TRAININGS_ROOT / dataset
    if not ds_dir.exists():
        continue

    dataset_root = MVTEC_AD_ROOT if dataset == "mvtec_ad" else MVTEC_LOCO_ROOT

    for sub in sorted([p.name for p in ds_dir.iterdir() if p.is_dir()]):
        maps_root = ANOMALY_ROOT / dataset / sub / "test"

        pix_auc, n_img_pix = pixel_auroc_stream(dataset_root, maps_root, sub, dataset_kind=dataset,
                                                max_pixels=3_000_000, seed=42)
        au_pro, n_img_pro = au_pro_stream_full(dataset_root, maps_root, sub, dataset_kind=dataset,
                                               pro_limit=0.3, n_thresh=100)

        # TensorBoard
        tb_dir = ds_dir / sub / "tensorboard"
        writer = SummaryWriter(log_dir=str(tb_dir))
        if not (pix_auc is None or math.isnan(pix_auc)):
            writer.add_scalar("test/pixel_auroc_stream", pix_auc, TRAIN_STEPS)
        if not (au_pro is None or math.isnan(au_pro)):
            writer.add_scalar("test/au_pro_0.3_stream", au_pro, TRAIN_STEPS)
        writer.flush(); writer.close()

        rows.append({
            "dataset": dataset,
            "subdataset": sub,
            "pixel_auroc_stream": pix_auc,
            "au_pro_0.3_stream": au_pro,
            "n_images_pixel": int(n_img_pix),
            "n_images_pro": int(n_img_pro),
        })

df = pd.DataFrame(rows).sort_values(["dataset","subdataset"])
out_csv = OUTPUT_DIR / "pixel_metrics_stream.csv"
df.to_csv(out_csv, index=False)
print("✅ Saved:", out_csv)
display(df)

"""## 10-

لینک‌ها خراب‌اند و ما متریک را خودمان محاسبه کردیم

اسکریپت‌های ارزیابی رسمی را ندارد
"""

# Commented out IPython magic to ensure Python compatibility.

# =======================================================
# 10) (Optional) Run official evaluation scripts (MVTec AD / LOCO)
#     و استخراج متریک‌ها برای گزارش PDF
# =======================================================
# اگر این مرحله را نمی‌خواهی، می‌توانی از آن عبور کنی و فقط از image-AUC استفاده کنی.

# %cd /content

EVAL_DIR = Path("/content/eval")
EVAL_DIR.mkdir(parents=True, exist_ok=True)

MVTEC_AD_EVAL_URL = "https://www.mydrive.ch/shares/60736/698155e0e6d0467c4ff6203b16a31dc9/download/439517473-1665667812/mvtec_ad_evaluation.tar.xz"
MVTEC_LOCO_EVAL_URL = "https://www.mydrive.ch/shares/48245/a4e9922c5efa93f57b6a0ff9f5c6b969/download/430648014-1646847095/mvtec_loco_ad_evaluation.tar.xz"

def dl_extract_eval(url, name):
    arc = EVAL_DIR/name
    if not arc.exists():
        !wget -q --show-progress -O "{arc}" "{url}"
    marker = EVAL_DIR/(name + ".extracted")
    if not marker.exists():
        !tar -xf "{arc}" -C "{EVAL_DIR}"
        marker.write_text("ok")

dl_extract_eval(MVTEC_AD_EVAL_URL, "mvtec_ad_evaluation.tar.xz")
dl_extract_eval(MVTEC_LOCO_EVAL_URL, "mvtec_loco_ad_evaluation.tar.xz")

# Patch for .tiff extension if needed (safe even if already supports it)
def patch_tiff_reader(file_path: Path):
    if not file_path.exists():
        return
    txt = file_path.read_text()
    if "exts=['.tiff'" in txt or 'exts=[".tiff"' in txt:
        return
    # try to patch read_tiff default exts list
    txt2 = re.sub(r"exts\s*=\s*\(\s*'\.tif'\s*\)", "exts=('.tif','.tiff')", txt)
    txt2 = re.sub(r"exts\s*=\s*\[\s*'\.tif'\s*\]", "exts=['.tif','.tiff']", txt2)
    if txt2 != txt:
        file_path.write_text(txt2)

# Attempt patch on common util files (best effort)
patch_tiff_reader(EVAL_DIR/"mvtec_ad_evaluation"/"evaluation"/"generic_util.py")

print("Eval dirs:")
!find "{EVAL_DIR}" -maxdepth 2 -type d -print

# Commented out IPython magic to ensure Python compatibility.
# =======================================================
# 10) Fix: get evaluation scripts WITHOUT broken myDrive tar links
#     - try to fetch from a GitHub fork that includes eval folders
#     - if not found, we will rely on our reliable custom metrics (Cell 9.5)
# =======================================================

# %cd /content
!rm -rf /content/eval
!mkdir -p /content/eval

# Try a repo known to reference/contain eval code
# %cd /content
!rm -rf EfficientAD-modify
!git clone --depth 1 https://github.com/qkhanh711/EfficientAD-modify.git

# Copy evaluation folders if exist
!ls -la EfficientAD-modify | head
!bash -lc "if [ -d EfficientAD-modify/mvtec_ad_evaluation ]; then cp -r EfficientAD-modify/mvtec_ad_evaluation /content/eval/; fi"
!bash -lc "if [ -d EfficientAD-modify/mvtec_loco_ad_evaluation ]; then cp -r EfficientAD-modify/mvtec_loco_ad_evaluation /content/eval/; fi"

print("Eval dirs now:")
!find /content/eval -maxdepth 2 -type d

# Check result
import os
has_ad   = os.path.isdir("/content/eval/mvtec_ad_evaluation")
has_loco = os.path.isdir("/content/eval/mvtec_loco_ad_evaluation")
print("has mvtec_ad_evaluation:", has_ad)
print("has mvtec_loco_ad_evaluation:", has_loco)

if not has_ad and not has_loco:
    print("\n⚠️ Eval scripts were not found in this repo.")
    print("✅ Use Cell 9.5 (reliable custom metrics) as your official evaluation for the report.")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

# Example: MVTec AD evaluation (if folder exists)
!python /content/eval/mvtec_loco_ad_evaluation/evaluate_experiment.py \
  --dataset_base_dir "/content/datasets/mvtec_anomaly_detection" \
  --anomaly_maps_dir "/content/outputs/efficientad_runs/anomaly_maps/mvtec_ad/" \
  --output_dir "/content/outputs/efficientad_runs/official_eval/mvtec_ad/" \
  --evaluated_objects bottle

"""## 11-"""

# =======================================================
# 11) Evaluate MVTec AD categories executed (produces metrics json)
# =======================================================
import subprocess, json
from pathlib import Path

ANOMALY_MAPS_AD = OUTPUT_DIR/"anomaly_maps"/"mvtec_ad"
DATASET_AD = Path(MVTEC_AD_ROOT)

OUT_METRICS_DIR = OUTPUT_DIR/"metrics"
OUT_METRICS_DIR.mkdir(parents=True, exist_ok=True)

ad_eval_script = EVAL_DIR/"mvtec_ad_evaluation"/"evaluate_experiment.py"

# eval only categories you trained
for obj in MVTEC_AD_OBJECTS:
    cmd = [
        "python", str(ad_eval_script),
        "--dataset_base_dir", str(DATASET_AD),
        "--anomaly_maps_dir", str(ANOMALY_MAPS_AD),
        "--output_dir", str(OUT_METRICS_DIR),
        "--evaluated_objects", obj,
        "--pro_integration_limit", "0.3"
    ]
    print("\nEVAL:", " ".join(cmd))
    subprocess.run(cmd, check=True)

print("\nMVTec AD evaluation done.")
!find "{OUT_METRICS_DIR}" -maxdepth 3 -type f -name "*.json" -print

"""## 12-"""

# =======================================================
# 12) Evaluate MVTec LOCO categories executed (produces metrics json)
# =======================================================
import subprocess
from pathlib import Path

ANOMALY_MAPS_LOCO = OUTPUT_DIR/"anomaly_maps"/"mvtec_loco"
DATASET_LOCO = Path(MVTEC_LOCO_ROOT)

loco_eval_script = EVAL_DIR/"mvtec_loco_ad_evaluation"/"evaluate_experiment.py"

for obj in MVTEC_LOCO_OBJECTS:
    cmd = [
        "python", str(loco_eval_script),
        "--dataset_base_dir", str(DATASET_LOCO),
        "--anomaly_maps_dir", str(ANOMALY_MAPS_LOCO),
        "--output_dir", str(OUT_METRICS_DIR),
        "--object_name", obj,
    ]
    print("\nEVAL:", " ".join(cmd))
    subprocess.run(cmd, check=True)

print("\nMVTec LOCO evaluation done.")
!find "{OUT_METRICS_DIR}" -maxdepth 4 -type f -name "*.json" -print

"""## 13-"""

# =======================================================
# 13) Build 1-page PDF comparison report
#     - خلاصه نتایج  + مقایسه با اعداد گزارش‌شده در مقاله/README
# =======================================================
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import json, glob, math

# Load our metrics (image auc from final_metrics.json)
metrics_df = pd.read_csv(OUTPUT_DIR/"metrics_summary.csv")
pixel_csv = OUTPUT_DIR/"pixel_metrics_custom.csv"
pixel_df = pd.read_csv(pixel_csv) if pixel_csv.exists() else None


# Paper reference (EfficientAD WACV 2024) — mean image AUROC numbers commonly reported for EfficientAD-M
paper_ref = {
    ("mvtec_ad", "medium"): 99.1,
    ("mvtec_loco", "medium"): 90.7,
}

# Compute mean over executed categories (not necessarily full dataset mean if you didn't run all)
summary_rows = []
for dataset in metrics_df["dataset"].unique():
    sub = metrics_df[metrics_df["dataset"]==dataset]
    mean_auc = sub["final_image_auc"].mean()
mean_pixel = None
mean_pro = None
if pixel_df is not None and len(pixel_df)>0:
    psub = pixel_df[pixel_df["dataset"]==dataset]
    if len(psub)>0:
        mean_pixel = float(psub["pixel_auroc"].mean())
        mean_pro = float(psub["au_pro_0.3"].mean())

    n = len(sub)
    ref = paper_ref.get((dataset, MODEL_SIZE), None)
    summary_rows.append({
        "dataset": dataset,
        "model_size": MODEL_SIZE,
        "categories_executed": n,
        "our_mean_image_auc": round(mean_auc, 3),
        "paper_mean_image_auc": ref,
        "gap": (round(mean_auc-ref, 3) if ref is not None else None),
        "our_mean_pixel_auroc": (round(mean_pixel, 3) if mean_pixel is not None and not math.isnan(mean_pixel) else None),
        "our_mean_au_pro@0.3": (round(mean_pro, 3) if mean_pro is not None and not math.isnan(mean_pro) else None)
    })

summary_df = pd.DataFrame(summary_rows)

# Make 1-page PDF
pdf_path = OUTPUT_DIR/"comparison_one_page.pdf"

fig = plt.figure(figsize=(11.69, 8.27))  # A4 landscape
plt.axis("off")
title = "EfficientAD – Verification Report (1 page)\n"
subtitle = f"Model: {MODEL_SIZE} | Train steps: {TRAIN_STEPS} | Penalty: {USE_PENALTY}"
plt.text(0.01, 0.95, title, fontsize=16, weight="bold")
plt.text(0.01, 0.90, subtitle, fontsize=11)

tbl = plt.table(
    cellText=summary_df.values,
    colLabels=summary_df.columns,
    loc="center",
    cellLoc="center"
)
tbl.auto_set_font_size(False)
tbl.set_fontsize(10)
tbl.scale(1, 1.6)

note = ("Note:\n"
        "- our_mean_image_auc is averaged over the categories YOU executed.\n"
        "- paper_mean_image_auc refers to mean over all categories in the official benchmark.\n"
        "- To reproduce paper numbers, run FULL category lists with TRAIN_STEPS=70000.")
plt.text(0.01, 0.08, note, fontsize=9)

plt.savefig(pdf_path, bbox_inches="tight")
plt.close(fig)

print("Saved PDF:", pdf_path)
print("You can download it from the file browser in Colab.")

"""## 10_13-"""

# =======================================================
# 10-13) Build metrics_summary.csv + 1-page PDF (no external eval scripts)
# =======================================================
from pathlib import Path
import json, math
import pandas as pd
import matplotlib.pyplot as plt

OUTPUT_DIR = Path("/content/outputs/efficientad_runs")
TRAININGS_ROOT = OUTPUT_DIR / "trainings"
pdf_path = OUTPUT_DIR / "comparison_one_page.pdf"

# ---- 1) collect image-level AUROC from final_metrics.json
rows = []
for dataset_dir in TRAININGS_ROOT.glob("*"):
    if not dataset_dir.is_dir():
        continue
    dataset = dataset_dir.name
    for sub_dir in dataset_dir.glob("*"):
        if not sub_dir.is_dir():
            continue
        sub = sub_dir.name
        fm = sub_dir / "final_metrics.json"
        if fm.exists():
            d = json.loads(fm.read_text())
            rows.append({
                "dataset": dataset,
                "subdataset": sub,
                "model_size": d.get("model_size"),
                "train_steps": d.get("train_steps"),
                "final_image_auc": d.get("final_image_auc"),
                "tb_dir": d.get("tb_dir"),
            })

metrics_df = pd.DataFrame(rows).sort_values(["dataset","subdataset"])
metrics_csv = OUTPUT_DIR / "metrics_summary.csv"
metrics_df.to_csv(metrics_csv, index=False)
print("✅ Saved:", metrics_csv)
display(metrics_df)

# ---- 2) load pixel metrics if exists
pixel_csv = OUTPUT_DIR / "pixel_metrics_stream.csv"
pixel_df = pd.read_csv(pixel_csv) if pixel_csv.exists() else pd.DataFrame()

# ---- 3) dataset-level summary (over executed categories only)
summary_rows = []
for dataset in metrics_df["dataset"].unique():
    subm = metrics_df[metrics_df["dataset"] == dataset]
    mean_img = float(subm["final_image_auc"].mean())

    pix = None
    pro = None
    if len(pixel_df) > 0:
        subp = pixel_df[pixel_df["dataset"] == dataset]
        if len(subp) > 0:
            pix = float(subp["pixel_auroc_stream"].mean()) if "pixel_auroc_stream" in subp else None
            pro = float(subp["au_pro_0.3_stream"].mean()) if "au_pro_0.3_stream" in subp else None

    summary_rows.append({
        "dataset": dataset,
        "categories_executed": int(len(subm)),
        "our_mean_image_auc": round(mean_img, 3),
        "our_mean_pixel_auroc": (round(pix, 3) if pix is not None and not math.isnan(pix) else None),
        "our_mean_au_pro@0.3": (round(pro, 3) if pro is not None and not math.isnan(pro) else None),
    })

summary_df = pd.DataFrame(summary_rows)

# ---- 4) 1-page PDF
fig = plt.figure(figsize=(11.69, 8.27))  # A4 landscape
plt.axis("off")

title = "EfficientAD – Verification Report (1 page)\n"
subtitle = f"Executed categories only (NOT full benchmark)."
plt.text(0.01, 0.95, title, fontsize=16, weight="bold")
plt.text(0.01, 0.90, subtitle, fontsize=11)

tbl = plt.table(
    cellText=summary_df.values,
    colLabels=summary_df.columns,
    loc="center",
    cellLoc="center"
)
tbl.auto_set_font_size(False)
tbl.set_fontsize(10)
tbl.scale(1, 1.6)

note = (
    "Notes:\n"
    "- Means are computed over the categories you actually ran (subset).\n"
    "- Full-paper reproduction requires downloading all categories + long training.\n"
    "- Pixel metrics logged to TensorBoard under test/pixel_* and test/au_pro_*.\n"
)
plt.text(0.01, 0.08, note, fontsize=9)

plt.savefig(pdf_path, bbox_inches="tight")
plt.close(fig)

print("✅ Saved PDF:", pdf_path)
print("Open Colab file browser to download.")