# -*- coding: utf-8 -*-
"""NN_HW1_MohammadAminKiani_4043644008.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14f7k7p5jlJAlvp9p9Hy1wiKGgY90-Opb

# Mohammad Amin Kiani 4043644008

## pc eng - AI 404

### NN-ex2 . ui.ac.ir

## 0- Needs
"""

# 1. Download dataset
!wget https://data.lhncbc.nlm.nih.gov/public/Malaria/cell_images.zip
!unzip cell_images.zip

# 2. Import libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

"""## 1- Preprocessing"""

# 3. Data preprocessing & augmentation
IMG_SIZE = 28
BATCH_SIZE = 32

datagen = ImageDataGenerator(
    rescale=0./1,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

train_generator = datagen.flow_from_directory(
    '/content/cell_images',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training'
)

val_generator = datagen.flow_from_directory(
    '/content/cell_images',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='validation'
)

"""## 2- Model"""

# 4. Build CNN model
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Dropout(0.3),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(1, activation='sigmoid')
])

# 5. Compile model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()

# 6. Train model
EPOCHS = 8
history = model.fit(train_generator, validation_data=val_generator, epochs=EPOCHS)

"""## 3- Plots"""

# 7. Plot results
plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.legend()
plt.show()

"""## 4- Evaluate"""

# 8. Evaluate model on test data
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    '/content/cell_images',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False
)

predictions = model.predict(test_generator)
pred_classes = (predictions > 0.5).astype("int32")

"""## 5- Reports"""

# 9. Confusion Matrix
cm = confusion_matrix(test_generator.classes, pred_classes)
sns.heatmap(cm, annot=True)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# 10. Classification Report
print(classification_report(test_generator.classes, pred_classes, target_names=['Parasitized','Uninfected']))

"""## Temp:"""

# 3. Data preprocessing & augmentation
IMG_SIZE = 128
BATCH_SIZE = 32

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

train_generator = datagen.flow_from_directory(
    '/content/cell_images',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training'
)

val_generator = datagen.flow_from_directory(
    '/content/cell_images',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='validation'
)

# 4. Build CNN model
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Dropout(0.3),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(1, activation='sigmoid')
])

# 5. Compile model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()

# 6. Train model
EPOCHS = 10
history = model.fit(train_generator, validation_data=val_generator, epochs=EPOCHS)

# 7. Plot results
plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.legend()
plt.show()

# 8. Evaluate model on test data
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    '/content/cell_images',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False
)

predictions = model.predict(test_generator)
pred_classes = (predictions > 0.5).astype("int32")

# 9. Confusion Matrix
cm = confusion_matrix(test_generator.classes, pred_classes)
sns.heatmap(cm, annot=True)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# 10. Classification Report
print(classification_report(test_generator.classes, pred_classes, target_names=['Parasitized','Uninfected']))

"""# Final"""

# =========================
# 0) Setup (Colab)
# =========================
!pip -q install thop tensorboard

import os, zipfile, random, math, time
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torch.utils.tensorboard import SummaryWriter

from PIL import Image
import matplotlib.pyplot as plt

from torchvision import transforms
from thop import profile

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# -------------------------
# 1) Download & unzip dataset
# -------------------------
data_url = "https://data.lhncbc.nlm.nih.gov/public/Malaria/cell_images.zip"
zip_path = "cell_images.zip"
root_dir = Path("cell_images")

if not Path(zip_path).exists():
    !wget -q {data_url} -O {zip_path}

if not root_dir.exists():
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(".")
print("Dataset root:", root_dir.resolve())

# Expected structure:
# cell_images/
#   Parasitized/
#   Uninfected/


# =========================
# 2) Custom Dataset (PyTorch)
# =========================
class MalariaDataset(torch.utils.data.Dataset):
    def __init__(self, root, transform=None):
        self.root = Path(root)
        self.transform = transform

        self.class_to_idx = {
            "Parasitized": 1,   # infected
            "Uninfected": 0     # healthy
        }

        self.samples = []
        for cls_name, y in self.class_to_idx.items():
            cls_dir = self.root / cls_name
            for img_path in cls_dir.glob("*.png"):
                self.samples.append((str(img_path), y))

        # Shuffle once for randomness (reproducible if you set seed)
        random.shuffle(self.samples)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, y = self.samples[idx]
        img = Image.open(img_path).convert("RGB")
        if self.transform:
            img = self.transform(img)
        y = torch.tensor([y], dtype=torch.float32)  # shape (1,) for BCELoss
        return img, y


transform = transforms.Compose([
    transforms.Resize((28, 28)),
    transforms.ToTensor(),  # converts to [0,1]
])

dataset = MalariaDataset(root_dir, transform=transform)
print("Total images:", len(dataset))  # should be 27558

# -------------------------
# 2.1) Show 3 samples from each class
# -------------------------
def show_samples(ds, n=3):
    inv = {0:"Uninfected", 1:"Parasitized"}
    picked = {0:0, 1:0}

    fig, axes = plt.subplots(2, n, figsize=(3*n, 6))
    for ax in axes.ravel():
        ax.axis("off")

    i = 0
    while picked[0] < n or picked[1] < n:
        x, y = ds[i]
        label = int(y.item())
        if picked[label] < n:
            r = label
            c = picked[label]
            img = x.permute(1,2,0).numpy()
            axes[r, c].imshow(img)
            axes[r, c].set_title(inv[label])
            picked[label] += 1
        i += 1

    plt.tight_layout()
    plt.show()

show_samples(dataset, n=3)

# -------------------------
# 2.2) Check balance
# -------------------------
count = {0:0, 1:0}
for _, y in dataset.samples:
    count[y] += 1
print("Counts:", count)
ratio = count[1] / (count[0] + 1e-9)
print("Parasitized/Uninfected ratio:", ratio)

if abs(count[0] - count[1]) / len(dataset) < 0.05:
    print("Dataset is approximately balanced (difference < 5%).")
else:
    print("Dataset is NOT well balanced.")


# =========================
# 3) Models
# =========================
class BaseCNN(nn.Module):
    # مطابق ساختار PDF: 4 Conv (k=3,pad=1,stride=1) + AdaptiveAvgPool2d + Linear + Sigmoid
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1),
            nn.ReLU(inplace=True),

            nn.Conv2d(16, 16, kernel_size=3, stride=1, padding=1),
            nn.ReLU(inplace=True),

            nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(inplace=True),

            nn.Conv2d(32, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(inplace=True),
        )
        self.pool = nn.AdaptiveAvgPool2d((1,1))
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.features(x)
        x = self.pool(x)
        x = self.classifier(x)
        return x


class SpecialConv(nn.Module):
    """
    ورودی: (B,32,H,W)
    تقسیم به دو بخش 16 و 16
    اعمال Conv(16->16,k=3,pad=1) فقط روی نیمه اول
    کانکت نیمه دوم بدون تغییر
    خروجی: (B,32,H,W)
    """
    def __init__(self):
        super().__init__()
        self.conv16 = nn.Conv2d(16, 16, kernel_size=3, stride=1, padding=1)

    def forward(self, x):
        x1, x2 = torch.split(x, 16, dim=1)   # channel dim
        y1 = self.conv16(x1)
        y = torch.cat([y1, x2], dim=1)
        return y


class CNNWithSpecial(nn.Module):
    def __init__(self):
        super().__init__()
        self.pre = nn.Sequential(
            nn.Conv2d(3, 16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,32, 3, 1, 1), nn.ReLU(inplace=True),
        )
        self.special = nn.Sequential(
            SpecialConv(),
            nn.ReLU(inplace=True)
        )
        self.pool = nn.AdaptiveAvgPool2d((1,1))
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.pre(x)
        x = self.special(x)
        x = self.pool(x)
        x = self.classifier(x)
        return x


class CNNWithSpecialAndPointwise(nn.Module):
    """
    بعد از لایه خاص، یک pointwise (1x1) می‌گذاریم تا mixing کانال‌ها بهتر شود.
    اینجا برای اینکه آزادی تنظیم داشته باشیم، 32->64 افزایش می‌دهیم و بعد classifier را مطابقش تغییر می‌دهیم.
    """
    def __init__(self):
        super().__init__()
        self.pre = nn.Sequential(
            nn.Conv2d(3, 16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,32, 3, 1, 1), nn.ReLU(inplace=True),
        )
        self.special = nn.Sequential(
            SpecialConv(),
            nn.ReLU(inplace=True)
        )
        self.pointwise = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=1, stride=1, padding=0),
            nn.ReLU(inplace=True)
        )
        self.pool = nn.AdaptiveAvgPool2d((1,1))
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.pre(x)
        x = self.special(x)
        x = self.pointwise(x)
        x = self.pool(x)
        x = self.classifier(x)
        return x


# =========================
# 4) FLOPs + Params report
# =========================
def count_params(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

def report_flops_params(model, input_shape=(1,3,28,28)):
    model = model.to(device)
    dummy = torch.randn(*input_shape).to(device)
    flops, params = profile(model, inputs=(dummy,), verbose=False)
    # thop returns MACs sometimes depending on ops; it reports as "FLOPs" in output here.
    return flops, params

models = {
    "ModelA_Base": BaseCNN(),
    "ModelB_Special": CNNWithSpecial(),
    "ModelC_Special+Pointwise": CNNWithSpecialAndPointwise(),
}

for name, m in models.items():
    flops, params_thop = report_flops_params(m)
    params = count_params(m)
    print(f"{name}:")
    print(f"  Trainable params (manual): {params:,}")
    print(f"  THOP params:             {params_thop:,}")
    print(f"  THOP FLOPs:              {flops:,}")
    print("-"*40)


# =========================
# 5) Train / Eval (8 epochs) + TensorBoard
# =========================
def accuracy_from_probs(probs, y_true):
    preds = (probs >= 0.5).float()
    return (preds.eq(y_true).float().mean()).item()

def train_one_model(model, run_name, train_loader, test_loader, epochs=8, lr=1e-3):
    model = model.to(device)
    criterion = nn.BCELoss()
    optimizer = optim.RMSprop(model.parameters(), lr=lr)

    writer = SummaryWriter(log_dir=f"runs/{run_name}")

    global_step = 0
    for epoch in range(1, epochs+1):
        model.train()
        train_loss = 0.0
        train_acc = 0.0

        for x, y in train_loader:
            x, y = x.to(device), y.to(device)

            optimizer.zero_grad()
            probs = model(x)  # sigmoid output
            loss = criterion(probs, y)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            train_acc += accuracy_from_probs(probs.detach(), y)

            writer.add_scalar("train/loss_step", loss.item(), global_step)
            global_step += 1

        train_loss /= len(train_loader)
        train_acc  /= len(train_loader)

        model.eval()
        test_loss = 0.0
        test_acc = 0.0
        with torch.no_grad():
            for x, y in test_loader:
                x, y = x.to(device), y.to(device)
                probs = model(x)
                loss = criterion(probs, y)
                test_loss += loss.item()
                test_acc  += accuracy_from_probs(probs, y)

        test_loss /= len(test_loader)
        test_acc  /= len(test_loader)

        writer.add_scalar("train/loss_epoch", train_loss, epoch)
        writer.add_scalar("train/acc_epoch", train_acc, epoch)
        writer.add_scalar("test/loss_epoch",  test_loss,  epoch)
        writer.add_scalar("test/acc_epoch",   test_acc,   epoch)

        print(f"[{run_name}] Epoch {epoch:02d}/{epochs} | "
              f"train loss {train_loss:.4f} acc {train_acc:.4f} | "
              f"test loss {test_loss:.4f} acc {test_acc:.4f}")

    writer.close()
    return model


# -------------------------
# 5.1) Train/test split
# -------------------------
torch.manual_seed(42)

train_size = int(0.8 * len(dataset))
test_size  = len(dataset) - train_size
train_ds, test_ds = random_split(dataset, [train_size, test_size])

batch_size = 128
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

# -------------------------
# 5.2) Train each model once (8 epochs)
# -------------------------
trained = {}
for name, model in models.items():
    trained[name] = train_one_model(model, run_name=name, train_loader=train_loader, test_loader=test_loader,
                                    epochs=8, lr=1e-3)

print("Done. To view TensorBoard:")
print("  %load_ext tensorboard")
print("  %tensorboard --logdir runs")

# Commented out IPython magic to ensure Python compatibility.
#   %load_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
#   %tensorboard --logdir runs

"""##### سیگموید از داخل مدل حذف شد"""

# =========================
# 0) Setup (Colab)
# =========================
!pip -q install tensorboard

import os, zipfile, random
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torch.utils.tensorboard import SummaryWriter

from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# -------------------------
# 1) Download & unzip dataset
# -------------------------
data_url = "https://data.lhncbc.nlm.nih.gov/public/Malaria/cell_images.zip"
zip_path = "cell_images.zip"
root_dir = Path("cell_images")

if not Path(zip_path).exists():
    !wget -q {data_url} -O {zip_path}

if not root_dir.exists():
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(".")
print("Dataset root:", root_dir.resolve())


# =========================
# 2) Dataset / Dataloader
# =========================
class MalariaDataset(torch.utils.data.Dataset):
    def __init__(self, root, transform=None):
        self.root = Path(root)
        self.transform = transform
        self.class_to_idx = {"Parasitized": 1, "Uninfected": 0}

        self.samples = []
        for cls_name, y in self.class_to_idx.items():
            for img_path in (self.root / cls_name).glob("*.png"):
                self.samples.append((str(img_path), y))
        random.shuffle(self.samples)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, y = self.samples[idx]
        img = Image.open(img_path).convert("RGB")
        if self.transform:
            img = self.transform(img)
        # BCEWithLogitsLoss expects float targets in {0,1}
        y = torch.tensor([y], dtype=torch.float32)
        return img, y

transform = transforms.Compose([
    transforms.Resize((28, 28)),
    transforms.ToTensor(),  # [0,1]
])

dataset = MalariaDataset(root_dir, transform=transform)
print("Total images:", len(dataset))

# Balance check
count = {0:0, 1:0}
for _, y in dataset.samples:
    count[y] += 1
print("Counts:", count)
print("Parasitized/Uninfected ratio:", count[1]/count[0])

# Show 3 samples each class
def show_samples(ds, n=3):
    inv = {0:"Uninfected", 1:"Parasitized"}
    picked = {0:0, 1:0}
    fig, axes = plt.subplots(2, n, figsize=(3*n, 6))
    for ax in axes.ravel():
        ax.axis("off")

    i = 0
    while picked[0] < n or picked[1] < n:
        x, y = ds[i]
        label = int(y.item())
        if picked[label] < n:
            r, c = label, picked[label]
            axes[r, c].imshow(x.permute(1,2,0).numpy())
            axes[r, c].set_title(inv[label])
            picked[label] += 1
        i += 1
    plt.tight_layout()
    plt.show()

show_samples(dataset, 3)

# Train/test split
torch.manual_seed(42)
train_size = int(0.8 * len(dataset))
test_size  = len(dataset) - train_size
train_ds, test_ds = random_split(dataset, [train_size, test_size])

batch_size = 128
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)


# =========================
# 3) Models (logits output, no sigmoid inside)
# =========================
class BaseCNN(nn.Module):
    # 4 Conv (k=3) + AdaptiveAvgPool + Linear -> logits
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,32, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(32,32, 3, 1, 1), nn.ReLU(inplace=True),
        )
        self.pool = nn.AdaptiveAvgPool2d((1,1))
        self.fc = nn.Linear(32, 1)  # logits

    def forward(self, x):
        x = self.features(x)
        x = self.pool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)
        return x  # logits


class SpecialConv(nn.Module):
    """
    input:  (B,32,H,W)
    split -> (B,16,H,W) + (B,16,H,W)
    conv3x3 only on first 16 channels (16->16, pad=1) then concat back -> (B,32,H,W)
    """
    def __init__(self):
        super().__init__()
        self.conv16 = nn.Conv2d(16, 16, 3, 1, 1)

    def forward(self, x):
        x1, x2 = torch.split(x, 16, dim=1)
        y1 = self.conv16(x1)
        return torch.cat([y1, x2], dim=1)


class CNNWithSpecial(nn.Module):
    def __init__(self):
        super().__init__()
        self.pre = nn.Sequential(
            nn.Conv2d(3, 16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,32, 3, 1, 1), nn.ReLU(inplace=True),
        )
        self.special = nn.Sequential(SpecialConv(), nn.ReLU(inplace=True))
        self.pool = nn.AdaptiveAvgPool2d((1,1))
        self.fc = nn.Linear(32, 1)

    def forward(self, x):
        x = self.pre(x)
        x = self.special(x)
        x = self.pool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)
        return x  # logits


class CNNWithSpecialAndPointwise(nn.Module):
    """
    After special conv, add pointwise 1x1 to improve channel mixing, then classifier.
    Here we set 32->64.
    """
    def __init__(self):
        super().__init__()
        self.pre = nn.Sequential(
            nn.Conv2d(3, 16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,16, 3, 1, 1), nn.ReLU(inplace=True),
            nn.Conv2d(16,32, 3, 1, 1), nn.ReLU(inplace=True),
        )
        self.special = nn.Sequential(SpecialConv(), nn.ReLU(inplace=True))
        self.pointwise = nn.Sequential(
            nn.Conv2d(32, 64, 1, 1, 0), nn.ReLU(inplace=True)
        )
        self.pool = nn.AdaptiveAvgPool2d((1,1))
        self.fc = nn.Linear(64, 1)

    def forward(self, x):
        x = self.pre(x)
        x = self.special(x)
        x = self.pointwise(x)
        x = self.pool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)
        return x  # logits


# =========================
# 4) FLOPs (طبق تعریف PDF)
# =========================
# Definition used:
# - One MAC = one multiply + one add = 2 FLOPs
# - Bias add (if exists) = 1 FLOP per output element
#
# We count FLOPs for Conv2d and Linear only (matching PDF-style layer FLOPs focus).

def trainable_params(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

@torch.no_grad()
def flops_pdf_style(model: nn.Module, input_shape=(1,3,28,28)) -> int:
    model = model.to(device).eval()
    flops_total = 0

    def conv2d_flops(layer: nn.Conv2d, x, y):
        # x: (B,Cin,H,W), y: (B,Cout,Hout,Wout)
        B, Cin, Hin, Win = x.shape
        B2, Cout, Hout, Wout = y.shape
        assert B == B2

        kH, kW = layer.kernel_size
        groups = layer.groups

        # MACs per output element = kH*kW*(Cin/groups)
        mac_per_out = kH * kW * (Cin // groups)

        # Total output elements = B*Cout*Hout*Wout
        out_elems = B * Cout * Hout * Wout

        # FLOPs = 2 * MACs
        flops = 2 * out_elems * mac_per_out

        # bias add
        if layer.bias is not None:
            flops += out_elems  # one add per output element

        return flops

    def linear_flops(layer: nn.Linear, x, y):
        # x: (B, in), y: (B, out)
        if x.dim() == 1:
            x = x.unsqueeze(0)
        B, in_f = x.shape
        B2, out_f = y.shape
        assert B == B2

        # MACs = B * in_f * out_f
        flops = 2 * B * in_f * out_f
        if layer.bias is not None:
            flops += B * out_f
        return flops

    hooks = []

    def hook_fn(module, inp, out):
        nonlocal flops_total
        x = inp[0]
        y = out
        if isinstance(module, nn.Conv2d):
            flops_total += conv2d_flops(module, x, y)
        elif isinstance(module, nn.Linear):
            flops_total += linear_flops(module, x, y)

    for m in model.modules():
        if isinstance(m, (nn.Conv2d, nn.Linear)):
            hooks.append(m.register_forward_hook(hook_fn))

    dummy = torch.randn(*input_shape).to(device)
    _ = model(dummy)

    for h in hooks:
        h.remove()

    return int(flops_total)


models = {
    "ModelA_Base": BaseCNN(),
    "ModelB_Special": CNNWithSpecial(),
    "ModelC_Special+Pointwise": CNNWithSpecialAndPointwise(),
}

for name, m in models.items():
    p = trainable_params(m)
    f = flops_pdf_style(m, input_shape=(1,3,28,28))
    print(f"{name}:")
    print(f"  Trainable params: {p:,}")
    print(f"  FLOPs (PDF-style, per 1 image forward): {f:,}")
    print("-"*50)


# =========================
# 5) Train / Eval (8 epochs) + TensorBoard
# =========================
def accuracy_from_logits(logits, y_true):
    probs = torch.sigmoid(logits)
    preds = (probs >= 0.5).float()
    return (preds.eq(y_true).float().mean()).item()

def train_one_model(model, run_name, train_loader, test_loader, epochs=8, lr=1e-3):
    model = model.to(device)
    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.RMSprop(model.parameters(), lr=lr)

    writer = SummaryWriter(log_dir=f"runs/{run_name}")
    global_step = 0

    for epoch in range(1, epochs+1):
        model.train()
        train_loss = 0.0
        train_acc  = 0.0

        for x, y in train_loader:
            x, y = x.to(device), y.to(device)

            optimizer.zero_grad()
            logits = model(x)
            loss = criterion(logits, y)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            train_acc  += accuracy_from_logits(logits.detach(), y)

            writer.add_scalar("train/loss_step", loss.item(), global_step)
            global_step += 1

        train_loss /= len(train_loader)
        train_acc  /= len(train_loader)

        model.eval()
        test_loss = 0.0
        test_acc  = 0.0
        with torch.no_grad():
            for x, y in test_loader:
                x, y = x.to(device), y.to(device)
                logits = model(x)
                loss = criterion(logits, y)
                test_loss += loss.item()
                test_acc  += accuracy_from_logits(logits, y)

        test_loss /= len(test_loader)
        test_acc  /= len(test_loader)

        writer.add_scalar("train/loss_epoch", train_loss, epoch)
        writer.add_scalar("train/acc_epoch",  train_acc,  epoch)
        writer.add_scalar("test/loss_epoch",  test_loss,  epoch)
        writer.add_scalar("test/acc_epoch",   test_acc,   epoch)

        print(f"[{run_name}] Epoch {epoch:02d}/{epochs} | "
              f"train loss {train_loss:.4f} acc {train_acc:.4f} | "
              f"test loss {test_loss:.4f} acc {test_acc:.4f}")

    writer.close()
    return model


trained = {}
for name, model in models.items():
    trained[name] = train_one_model(
        model, run_name=name,
        train_loader=train_loader, test_loader=test_loader,
        epochs=8, lr=1e-3
    )

print("Done. TensorBoard:")
print("  %load_ext tensorboard")
print("  %tensorboard --logdir runs")

# Commented out IPython magic to ensure Python compatibility.
#   %load_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
#   %tensorboard --logdir runs